# Step 0. 실행 환경 구축

Qwen3.5-122B-A10B-GPTQ-Int4 모델을 A100 80GB 단일 GPU에서
vLLM으로 실행하기 위한 환경을 구성한다.

검증 완료된 실행 환경:

- Python 3.13.x
- PyTorch 2.13.0+cu132
- CUDA 13.2
- TorchVision 0.28.0+cu132
- vLLM 0.29.1rc1.dev567+g8d16ca6cc
- GPU: NVIDIA A100-SXM4-80GB

이 단계에서는 모델과 데이터를 사용하지 않고,
122B 모델을 안정적으로 실행할 수 있는 라이브러리 환경만 구성한다.

설치 완료 후 런타임을 한 번 재시작하고 Step 1을 진행한다.

In [8]:
# ============================================================
# [STEP 0] QWEN3.5-122B WORKING ENVIRONMENT
#
# 실제 성공 환경 재현:
# Python      : 3.13.x
# Torch       : 2.13.0+cu132
# CUDA        : 13.2
# TorchVision : 0.28.0+cu132
# vLLM        : 0.29.1rc1.dev567+g8d16ca6cc
# TorchAudio  : NOT INSTALLED
#
# 이번 셀에서:
# 1. Torch / TorchVision CU132 설치
# 2. vLLM dev567 설치
# 3. vLLM이 요구하는 dependencies 전부 자동 설치
# 4. cbor2 / openai-harmony / msgspec 포함
# 5. fresh subprocess에서 from vllm import LLM 검증
#
# 모델 다운로드 X
# 데이터 사용 X
#
# 완료 후 세션 다시 시작 1회
# ============================================================

import sys
import subprocess
import importlib.metadata as md


# ============================================================
# CONFIG
# ============================================================

VLLM_COMMIT = (
    "8d16ca6cc21931481f6c6f9ec0365874a80c6bb2"
)

VLLM_VERSION = (
    "0.29.1rc1.dev567+g8d16ca6cc"
)

VLLM_INDEX = (
    f"https://wheels.vllm.ai/{VLLM_COMMIT}"
)


print("=" * 72)
print("STEP 0 : BUILD EXACT 122B ENVIRONMENT")
print("=" * 72)


# ============================================================
# 1. REMOVE CONFLICTING PACKAGES
# ============================================================

print("\n===== [0-0] REMOVE OLD STACK =====")

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "uninstall",
        "-y",
        "torch",
        "torchvision",
        "torchaudio",
        "vllm",
    ],
    check=False,
)


# ============================================================
# 2. TORCH 2.13 + CUDA 13.2
# ============================================================

print("\n===== [0-1] INSTALL TORCH CU132 =====")

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "install",
        "--no-cache-dir",
        "--force-reinstall",

        "torch==2.13.0+cu132",
        "torchvision==0.28.0+cu132",

        "--index-url",
        "https://download.pytorch.org/whl/cu132",
    ],
    check=True,
)


# ============================================================
# 3. EXACT vLLM dev567
#
# 먼저 wheel 자체만 설치.
# 그 다음 metadata에서 dependency를 전부 읽어서 설치.
# ============================================================

print("\n===== [0-2] INSTALL EXACT vLLM dev567 =====")

subprocess.run(
    [
        "uv",
        "pip",
        "install",

        "--reinstall",
        "--no-deps",
        "--pre",

        "vllm",

        "--index-url",
        VLLM_INDEX,
    ],
    check=True,
)


# ============================================================
# 4. READ ALL vLLM DEPENDENCIES
#
# import vllm 하지 않음.
# package metadata만 읽기 때문에 안전.
# ============================================================

print("\n===== [0-3] RESOLVE ALL vLLM DEPENDENCIES =====")

from packaging.requirements import Requirement


requires = md.requires("vllm") or []

deps = []


for req_text in requires:

    try:
        req = Requirement(req_text)

    except Exception:
        continue


    # --------------------------------------------------------
    # 현재 Python/platform에서 marker가 false면 제외
    # --------------------------------------------------------

    if (
        req.marker is not None
        and not req.marker.evaluate()
    ):
        continue


    name = req.name.lower()


    # --------------------------------------------------------
    # 이미 우리가 정확한 wheel로 관리하는 것들
    # --------------------------------------------------------

    if name in {
        "torch",
        "torchvision",
        "torchaudio",
        "vllm",
    }:
        continue


    deps.append(
        req_text
    )


# 중복 제거
deps = list(
    dict.fromkeys(deps)
)


print(
    "vLLM dependencies:",
    len(deps)
)


# ============================================================
# 5. INSTALL ALL DEPENDENCIES
#
# 여기서:
# cbor2
# msgspec
# openai-harmony
# 등 dev567이 요구하는 패키지를 전부 설치
# ============================================================

print("\n===== [0-4] INSTALL ALL vLLM DEPENDENCIES =====")


if deps:

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",

            "--upgrade",

            *deps,
        ],
        check=True,
    )


# ============================================================
# 6. TORCHAUDIO 제거 유지
#
# 성공 환경에서도 NOT INSTALLED
# ============================================================

subprocess.run(
    [
        sys.executable,
        "-m",
        "pip",
        "uninstall",
        "-y",
        "torchaudio",
    ],
    check=False,
)


# ============================================================
# 7. FRESH PROCESS VERIFY
#
# 현재 notebook kernel은 기존 module을 들고 있을 수 있으므로
# 새 Python process에서 실제 import 검증.
# ============================================================

print("\n===== [0-5] FRESH PROCESS VERIFY =====")


verify_code = r'''
import sys
import importlib.metadata as md

import torch
import torchvision
import vllm

from vllm import LLM
from vllm import SamplingParams
from vllm.sampling_params import StructuredOutputsParams


print("Python      :", sys.version.split()[0])
print("Torch       :", torch.__version__)
print("CUDA        :", torch.version.cuda)
print("TorchVision :", torchvision.__version__)
print("vLLM        :", vllm.__version__)

try:
    print("TorchAudio  :", md.version("torchaudio"))
except Exception:
    print("TorchAudio  : NOT INSTALLED")

print(
    "GPU         :",
    torch.cuda.get_device_name(0)
)

print(
    "VRAM        :",
    round(
        torch.cuda.get_device_properties(0)
        .total_memory / 1024**3,
        2,
    ),
    "GB",
)


assert torch.__version__.startswith(
    "2.13.0+cu132"
), torch.__version__

assert torch.version.cuda == "13.2"

assert torchvision.__version__.startswith(
    "0.28.0+cu132"
), torchvision.__version__

assert (
    "0.29.1rc1.dev567"
    in vllm.__version__
), vllm.__version__


print()
print("LLM IMPORT                     : OK")
print("SamplingParams IMPORT          : OK")
print("StructuredOutputsParams IMPORT : OK")

print()
print("=" * 60)
print("✅ STEP 0 ENVIRONMENT SUCCESS")
print("=" * 60)
'''


result = subprocess.run(
    [
        sys.executable,
        "-c",
        verify_code,
    ],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
)


print(
    result.stdout
)


if result.returncode != 0:

    raise RuntimeError(
        "❌ STEP 0 VERIFY FAILED\n\n"
        + result.stdout
    )


# ============================================================
# DONE
# ============================================================

print("\n" + "=" * 72)

print("✅ STEP 0 COMPLETE")

print("=" * 72)

print(
    "\n이제 Colab 메뉴에서 딱 한 번:\n"
    "런타임 -> 세션 다시 시작\n\n"
    "연결 해제 X\n"
    "런타임 삭제 X\n"
    "data.zip 다시 풀기 X\n"
    "122B 다시 다운로드 X\n"
)

print("=" * 72)

========================================================================
STEP 0 : BUILD EXACT 122B ENVIRONMENT
========================================================================

===== [0-0] REMOVE OLD STACK =====

===== [0-1] INSTALL TORCH CU132 =====

===== [0-2] INSTALL EXACT vLLM dev567 =====

===== [0-3] RESOLVE ALL vLLM DEPENDENCIES =====
vLLM dependencies: 72

===== [0-4] INSTALL ALL vLLM DEPENDENCIES =====

===== [0-5] FRESH PROCESS VERIFY =====
Python      : 3.13.15
Torch       : 2.13.0+cu132
CUDA        : 13.2
TorchVision : 0.28.0+cu132
vLLM        : 0.29.1rc1.dev567+g8d16ca6cc
TorchAudio  : NOT INSTALLED
GPU         : NVIDIA A100-SXM4-80GB
VRAM        : 79.25 GB

LLM IMPORT                     : OK
SamplingParams IMPORT          : OK
StructuredOutputsParams IMPORT : OK

============================================================
✅ STEP 0 ENVIRONMENT SUCCESS
============================================================


========================================================================
✅ STEP 0 COMPLETE
========================================================================

이제 Colab 메뉴에서 딱 한 번:
런타임 -> 세션 다시 시작

연결 해제 X
런타임 삭제 X
data.zip 다시 풀기 X
122B 다시 다운로드 X

========================================================================

# Step 1. Qwen3.5-122B 모델 준비 및 GPU 로드

Qwen3.5-122B-A10B-GPTQ-Int4 모델을 준비하고
A100 80GB 단일 GPU에 vLLM으로 로드한다.

모델이 로컬에 존재하지 않으면 Hugging Face에서 다운로드하고,
이미 정상적으로 다운로드되어 있으면 기존 파일을 재사용한다.

검증된 모델 로드 설정:

- model: Qwen/Qwen3.5-122B-A10B-GPTQ-Int4
- quantization: moe_wna16
- dtype: bfloat16
- tensor_parallel_size: 1
- max_model_len: 2048
- max_num_seqs: 1
- gpu_memory_utilization: 0.99
- enforce_eager: True
- multimodal image input: 1
- trust_remote_code: True
- seed: 42

모델 로드가 완료되면 `llm_122b` 객체를 유지한 상태로
이후 Image-only VQA 추론을 진행한다.

In [1]:
# ============================================================
# [STEP 1] QWEN3.5-122B PREPARE + LOAD
#
# 동작:
# 1. 로컬 모델이 없거나 불완전하면 snapshot_download
# 2. 이미 완전하면 다운로드 생략
# 3. llm_122b가 이미 메모리에 있으면 재로드 생략
# 4. 새 세션이면 122B GPU 로드
#
# 따라서:
# - 지금 실행해도 안전
# - 새 런타임에서도 단독 실행 가능
# ============================================================

import time
import shutil
from pathlib import Path

import torch
import torchvision
import vllm

from huggingface_hub import snapshot_download
from vllm import LLM


# ============================================================
# 0. CONFIG
# ============================================================

MODEL_ID = "Qwen/Qwen3.5-122B-A10B-GPTQ-Int4"

MODEL_DIR = Path(
    "/content/Qwen3.5-122B-A10B-GPTQ-Int4"
)


# ============================================================
# 1. ENV VERIFY
# ============================================================

print("=" * 72)
print("STEP 1 : QWEN3.5-122B PREPARE + LOAD")
print("=" * 72)

print("Torch       :", torch.__version__)
print("CUDA        :", torch.version.cuda)
print("TorchVision :", torchvision.__version__)
print("vLLM        :", vllm.__version__)
print("GPU         :", torch.cuda.get_device_name(0))

print(
    "VRAM        :",
    round(
        torch.cuda.get_device_properties(0).total_memory
        / 1024**3,
        2,
    ),
    "GB",
)


assert torch.__version__.startswith(
    "2.13.0+cu132"
), torch.__version__

assert torch.version.cuda == "13.2"

assert torchvision.__version__.startswith(
    "0.28.0+cu132"
), torchvision.__version__

assert "0.29.1rc1.dev567" in vllm.__version__


print("\n✅ ENVIRONMENT VERIFIED")


# ============================================================
# 2. MODEL FILE CHECK
# ============================================================

def model_is_complete():

    if not MODEL_DIR.exists():
        return False

    if not (MODEL_DIR / "config.json").exists():
        return False

    weights = list(
        MODEL_DIR.glob("*.safetensors")
    )

    if not weights:
        return False

    total_gb = sum(
        p.stat().st_size
        for p in weights
    ) / 1024**3

    # 현재 정상 다운로드 결과 약 73.45GB
    if total_gb < 70:
        return False

    return True


# ============================================================
# 3. DOWNLOAD IF NEEDED
# ============================================================

if model_is_complete():

    weights = list(
        MODEL_DIR.glob("*.safetensors")
    )

    total_gb = sum(
        p.stat().st_size
        for p in weights
    ) / 1024**3

    print("\n===== MODEL CHECK =====")
    print("✅ EXISTING MODEL READY")
    print("MODEL DIR   :", MODEL_DIR)
    print("WEIGHT FILES:", len(weights))
    print("WEIGHT SIZE :", round(total_gb, 2), "GB")

else:

    free_gb = (
        shutil.disk_usage("/content").free
        / 1024**3
    )

    print("\n===== MODEL DOWNLOAD =====")
    print("DISK FREE:", round(free_gb, 2), "GB")

    assert free_gb > 85, (
        f"❌ 모델 다운로드 공간 부족: {free_gb:.2f}GB"
    )

    t0 = time.time()

    snapshot_download(
        repo_id=MODEL_ID,
        local_dir=str(MODEL_DIR),
        max_workers=8,
    )

    print(
        "✅ DOWNLOAD COMPLETE:",
        round(
            (time.time() - t0) / 60,
            2,
        ),
        "min",
    )


# ============================================================
# 4. FINAL FILE VERIFY
# ============================================================

assert model_is_complete(), (
    "❌ 모델 다운로드/파일 검증 실패"
)

weights = list(
    MODEL_DIR.glob("*.safetensors")
)

total_gb = sum(
    p.stat().st_size
    for p in weights
) / 1024**3


print("\n===== MODEL READY =====")
print("WEIGHT FILES:", len(weights))
print("WEIGHT SIZE :", round(total_gb, 2), "GB")


# ============================================================
# 5. LOAD OR REUSE
# ============================================================

if (
    "llm_122b" in globals()
    and llm_122b is not None
):

    print("\n" + "=" * 72)
    print("✅ EXISTING llm_122b REUSED")
    print("OBJECT:", type(llm_122b))
    print("=" * 72)

else:

    print("\n===== START 122B LOAD =====")

    t0 = time.time()

    llm_122b = LLM(

        model=str(MODEL_DIR),

        tensor_parallel_size=1,

        quantization="moe_wna16",

        dtype="bfloat16",

        max_model_len=2048,

        max_num_seqs=1,

        gpu_memory_utilization=0.99,

        enforce_eager=True,

        limit_mm_per_prompt={
            "image": 1,
            "video": 0,
        },

        trust_remote_code=True,

        seed=42,
    )

    elapsed = time.time() - t0

    print("\n" + "=" * 72)
    print("✅ STEP 1 122B LOAD SUCCESS")
    print("=" * 72)

    print(
        "LOAD TIME:",
        round(elapsed / 60, 2),
        "min",
    )

    print(
        "OBJECT:",
        type(llm_122b),
    )

    print("=" * 72)

========================================================================
STEP 1 : QWEN3.5-122B PREPARE + LOAD
========================================================================
Torch       : 2.13.0+cu132
CUDA        : 13.2
TorchVision : 0.28.0+cu132
vLLM        : 0.29.1rc1.dev567+g8d16ca6cc
GPU         : NVIDIA A100-SXM4-80GB
VRAM        : 79.25 GB

✅ ENVIRONMENT VERIFIED

===== MODEL CHECK =====
✅ EXISTING MODEL READY
MODEL DIR   : /content/Qwen3.5-122B-A10B-GPTQ-Int4
WEIGHT FILES: 39
WEIGHT SIZE : 73.45 GB

===== MODEL READY =====
WEIGHT FILES: 39
WEIGHT SIZE : 73.45 GB

===== START 122B LOAD =====
INFO 09-25 06:15:26 [api_utils.py:286] non-default args: {'trust_remote_code': True, 'dtype': 'bfloat16', 'seed': 42, 'max_model_len': 2048, 'gpu_memory_utilization': 0.99, 'max_num_seqs': 1, 'disable_log_stats': True, 'quantization': 'moe_wna16', 'enforce_eager': True, 'limit_mm_per_prompt': {'image': 1, 'video': 0}, 'model': '/content/Qwen3.5-122B-A10B-GPTQ-Int4'}
INFO 09-25 06:15:26 [model.py:696] Resolved architecture: Qwen3_5MoeForConditionalGeneration
INFO 09-25 06:15:26 [model.py:2104] Using max model len 2048
WARNING 09-25 06:15:26 [model.py:1066] Model does not support mm_device_do_normalize, forcing mm_device_do_normalize = False.
INFO 09-25 06:15:28 [scheduler.py:302] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 09-25 06:15:28 [config.py:628] Mamba cache mode is set to 'align' for Qwen3_5MoeForConditionalGeneration by default when prefix caching is enabled
WARNING 09-25 06:15:28 [vllm.py:1607] Enforce eager set, disabling torch.compile, CUDAGraphs, and JIT kernel warmup. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none and --kernel_config.enable_jit_warmup=False
WARNING 09-25 06:15:28 [vllm.py:1633] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
INFO 09-25 06:15:28 [kernel.py:408] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['vllm_c', 'native'], fused_add_rms_norm=['vllm_c', 'native'], gelu_and_mul_sparse=['triton', 'native'])
INFO 09-25 06:15:28 [vllm.py:1843] Cudagraph is disabled under eager mode
INFO 09-25 06:15:28 [compilation.py:331] Enabled custom fusions: norm_quant, act_quant

[transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.

WARNING 09-25 06:15:45 [system_utils.py:156] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized
INFO 09-25 06:16:11 [base.py:251] Multi-modal warmup completed in 26.418s
INFO 09-25 06:19:04 [hf.py:642] Detected the chat template content format to be 'openai'. You can set `--chat-template-content-format` to override this.

========================================================================
✅ STEP 1 122B LOAD SUCCESS
========================================================================
LOAD TIME: 3.64 min
OBJECT: <class 'vllm.entrypoints.llm.LLM'>
========================================================================

# Step 2. Image-only 성능 검증

Qwen3.5-122B 모델의 VQA 성능을 확인하기 위해
정답이 존재하는 clean train 데이터 중 앞 1,000개를 대상으로 검증한다.

이전 실험에서는 OCR 및 Object Detection 정보를 프롬프트에 추가했지만,
오히려 모델의 이미지 이해를 방해하며 정확도가 하락했다.

따라서 최종 전략에서는 별도의 OCR/DINO 정보를 사용하지 않고
다음 정보만 122B 모델에 입력한다.

- 실제 이미지
- 질문
- 선택지 a / b / c / d

추론 설정:

- enable_thinking=False
- temperature=0.0
- structured output: a / b / c / d
- max_tokens=2

1,000개 Image-only 검증 결과:

**984 / 1000 = 98.4%**

따라서 이후 Test 데이터 추론에서도
동일한 Image-only 설정을 기본 추론 방식으로 사용한다.

In [3]:
# ============================================================
# [STEP 2-3 PREP] IMAGE-ONLY 데이터 환경 복구
#
# 세션 재시작 후:
# - Drive mount
# - clean CSV 다시 로드
# - DATA_ROOT 복구
# - 깨진 image-only 결과 파일 제거
# - 1000개 이미지 존재 확인
# ============================================================

from pathlib import Path

import pandas as pd
from google.colab import drive


# ============================================================
# 0. MODEL CHECK
# ============================================================

assert (
    "llm_122b" in globals()
    and llm_122b is not None
), "❌ Step 1 모델 로드부터 필요합니다."

print("✅ llm_122b:", type(llm_122b))


# ============================================================
# 1. DRIVE
# ============================================================

drive.mount(
    "/content/drive"
)


# ============================================================
# 2. PATH
# ============================================================

CLEAN_CSV = Path(
    "/content/drive/MyDrive/"
    "cleaning_data/"
    "train_combined_clean.csv"
)

DATA_ROOT = Path(
    "/content/ssafy_data"
)

OUT_CSV = Path(if "status" in old.columns:
    "/content/drive/MyDrive/"
    "cleaning_data/"
    "122b_eval/"
    "122b_image_only_1000.csv"
)


assert CLEAN_CSV.exists(), (
    f"❌ CSV 없음: {CLEAN_CSV}"
)

assert DATA_ROOT.exists(), (
    f"❌ DATA_ROOT 없음: {DATA_ROOT}"
)


# ============================================================
# 3. CSV RELOAD
# ============================================================

df = pd.read_csv(
    CLEAN_CSV
)


required_cols = [
    "id",
    "path",
    "question",
    "a",
    "b",
    "c",
    "d",
    "answer",
]


missing = [
    c
    for c in required_cols
    if c not in df.columns
]


assert not missing, (
    f"❌ 컬럼 누락: {missing}"
)


df["answer"] = (
    df["answer"]
    .astype(str)
    .str.strip()
    .str.lower()
)


df["source"] = (
    df["path"]
    .astype(str)
    .str.replace("\\", "/", regex=False)
    .str.split("/")
    .str[0]
    .str.lower()
)


# ============================================================
# 4. VERIFY
# ============================================================

print("\n===== CLEAN DATA =====")

print(
    "ROWS:",
    len(df)
)

print(
    "SOURCE:",
    df["source"]
    .value_counts()
    .to_dict()
)


assert len(df) == 7169, (
    f"❌ 예상 7169행, 실제 {len(df)}행"
)


first_1000_exists = df.iloc[:1000]["path"].map(
    lambda p:
    (DATA_ROOT / str(p)).exists()
)


print(
    "FIRST 1000 IMAGES:",
    int(first_1000_exists.sum()),
    "/ 1000"
)


assert first_1000_exists.all(), (
    "❌ 첫 1000개 이미지 중 누락 있음"
)


# ============================================================
# 6. READY
# ============================================================

print("\n" + "=" * 72)
print("✅ STEP 2-3 PREP COMPLETE")
print("=" * 72)

print("df        :", len(df))
print("DATA_ROOT :", DATA_ROOT)
print("MODEL     :", type(llm_122b))
print("=" * 72)

✅ llm_122b: <class 'vllm.entrypoints.llm.LLM'>
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

===== CLEAN DATA =====
ROWS: 7169
SOURCE: {'train': 5527, 'dev': 1642}
FIRST 1000 IMAGES: 1000 / 1000

기존 image-only 파일: 203 rows
{'error': 203}
✅ EngineDead 결과 파일 삭제

========================================================================
✅ STEP 2-3 PREP COMPLETE
========================================================================
df        : 7169
DATA_ROOT : /content/ssafy_data
MODEL     : <class 'vllm.entrypoints.llm.LLM'>
========================================================================

In [6]:
# ============================================================
# [STEP 2-3] IMAGE-ONLY 1000 SAMPLE SMOKE TEST
#
# 같은 clean dataset의 앞 1000개를 사용
#
# OCR X
# DINO X
#
# 실제 이미지 + question + a/b/c/d 만 사용
#
# 기존 OCR/DINO 결과와 별도 저장
# ============================================================

import os
import time
import inspect
import pandas as pd

from pathlib import Path
from PIL import Image

from vllm import SamplingParams
from vllm.sampling_params import StructuredOutputsParams


# ============================================================
# 0. CONFIG
# ============================================================

SMOKE_N = 1000

OUT_DIR = Path(
    "/content/drive/MyDrive/"
    "cleaning_data/"
    "122b_eval"
)

OUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


OUT_CSV = (
    OUT_DIR
    / "122b_image_only_1000.csv"
)


assert (
    "llm_122b" in globals()
    and llm_122b is not None
)

assert len(df) >= SMOKE_N


# ============================================================
# 1. EXACT SAME 1000 ROWS
# ============================================================

smoke_df = (
    df
    .iloc[:SMOKE_N]
    .copy()
    .reset_index(drop=True)
)


if "source" not in smoke_df.columns:

    smoke_df["source"] = (
        smoke_df["path"]
        .astype(str)
        .str.replace("\\", "/", regex=False)
        .str.split("/")
        .str[0]
        .str.lower()
    )


smoke_df["answer"] = (
    smoke_df["answer"]
    .astype(str)
    .str.strip()
    .str.lower()
)


print("=" * 78)
print("122B IMAGE-ONLY 1000 SMOKE TEST")
print("=" * 78)

print("SAMPLES :", len(smoke_df))
print("OUTPUT  :", OUT_CSV)


# ============================================================
# 2. IMAGE-ONLY SYSTEM PROMPT
# ============================================================

SYSTEM_PROMPT = (
    "당신은 이미지 기반 4지선다 VQA 전문가입니다.\n"
    "이미지를 가장 중요한 근거로 사용하고 "
    "질문과 선택지를 신중하게 비교하세요.\n"
    "최종 답은 반드시 a, b, c, d 중 "
    "소문자 한 글자로만 출력하세요."
)


def build_image_only_prompt(
    question,
    a,
    b,
    c,
    d,
):

    return (
        f"질문: {question}\n"
        f"(a) {a}\n"
        f"(b) {b}\n"
        f"(c) {c}\n"
        f"(d) {d}\n\n"
        "정답:"
    )


# ============================================================
# 3. STRUCTURED OUTPUT
# ============================================================

choice_constraint = StructuredOutputsParams(
    choice=[
        "a",
        "b",
        "c",
        "d",
    ]
)


sampling_params_image_only = SamplingParams(
    temperature=0.0,
    max_tokens=2,
    structured_outputs=choice_constraint,
)


# ============================================================
# 4. RESUME
# ============================================================

results = {}


if OUT_CSV.exists():

    old = pd.read_csv(
        OUT_CSV
    )

    for rec in (
        old
        .drop_duplicates(
            "id",
            keep="last"
        )
        .to_dict("records")
    ):

        results[
            str(rec["id"])
        ] = rec


done_ids = {
    k
    for k, v in results.items()
    if str(
        v.get(
            "status",
            ""
        )
    ) == "ok"
}


print(
    "RESUME  :",
    len(done_ids),
    "/",
    SMOKE_N
)


# ============================================================
# 5. SAVE
# ============================================================

def save_image_only():

    x = pd.DataFrame(
        list(
            results.values()
        )
    )

    tmp = Path(
        str(OUT_CSV)
        + ".tmp"
    )

    x.to_csv(
        tmp,
        index=False,
        encoding="utf-8-sig",
    )

    os.replace(
        tmp,
        OUT_CSV,
    )


# ============================================================
# 6. TQDM SUPPORT
# ============================================================

SUPPORTS_USE_TQDM = (
    "use_tqdm"
    in inspect.signature(
        llm_122b.chat
    ).parameters
)


# ============================================================
# 7. LOOP
# ============================================================

for idx, row in smoke_df.iterrows():

    img_id = str(
        row["id"]
    )


    if img_id in done_ids:
        continue


    gt = (
        str(
            row["answer"]
        )
        .strip()
        .lower()
    )


    image_path = (
        DATA_ROOT
        / str(
            row["path"]
        )
    )


    t0 = time.time()


    try:

        assert image_path.exists()


        with Image.open(
            image_path
        ) as im:

            image = (
                im
                .convert("RGB")
                .copy()
            )


        messages = [

            {
                "role":
                    "system",

                "content":
                    SYSTEM_PROMPT,
            },

            {
                "role":
                    "user",

                "content": [

                    {
                        "type":
                            "image_pil",

                        "image_pil":
                            image,
                    },

                    {
                        "type":
                            "text",

                        "text":
                            build_image_only_prompt(

                                row["question"],

                                row["a"],
                                row["b"],
                                row["c"],
                                row["d"],
                            ),
                    },
                ],
            },
        ]


        kwargs = dict(

            messages=
                messages,

            sampling_params=
                sampling_params_image_only,

            chat_template_kwargs={
                "enable_thinking":
                    False
            },
        )


        if SUPPORTS_USE_TQDM:

            kwargs[
                "use_tqdm"
            ] = False


        outputs = llm_122b.chat(
            **kwargs
        )


        pred = (
            outputs[0]
            .outputs[0]
            .text
            .strip()
            .lower()
        )


        assert pred in {
            "a",
            "b",
            "c",
            "d",
        }


        correct = int(
            pred == gt
        )


        status = "ok"
        error = ""


    except Exception as e:

        pred = ""
        correct = 0
        status = "error"
        error = repr(e)


    elapsed = (
        time.time()
        - t0
    )


    results[
        img_id
    ] = {

        "idx":
            int(idx),

        "id":
            img_id,

        "source":
            row["source"],

        "path":
            row["path"],

        "gt_answer":
            gt,

        "image_only_answer":
            pred,

        "correct":
            correct,

        "elapsed_sec":
            round(
                elapsed,
                4
            ),

        "status":
            status,

        "error":
            error,
    }


    if status == "ok":

        done_ids.add(
            img_id
        )


    save_image_only()


    current = pd.DataFrame(
        list(
            results.values()
        )
    )


    ok = current[
        current["status"]
        == "ok"
    ]


    correct_n = int(
        ok["correct"]
        .astype(int)
        .sum()
    )


    total_n = len(
        ok
    )


    acc = (
        correct_n / total_n
        if total_n
        else 0
    )


    mark = (
        "✅"
        if correct
        else "❌"
    )


    print(

        f"[{total_n:04d}/{SMOKE_N}] "

        f"{img_id} | "

        f"PRED={pred} "
        f"GT={gt} "

        f"{mark} | "

        f"ACC="
        f"{correct_n}/{total_n}="
        f"{acc:.4f} | "

        f"{elapsed:.2f}s",

        flush=True,
    )


# ============================================================
# 8. FINAL
# ============================================================

final = pd.DataFrame(
    list(
        results.values()
    )
)


ok = final[
    final["status"]
    == "ok"
]


correct_n = int(
    ok["correct"]
    .astype(int)
    .sum()
)


total_n = len(
    ok
)


acc = (
    correct_n / total_n
    if total_n
    else 0
)


print("\n" + "=" * 78)

print(
    "✅ IMAGE-ONLY 1000 COMPLETE"
)

print("=" * 78)

print(
    f"ACCURACY: "
    f"{correct_n}/{total_n} "
    f"= {acc:.6f}"
)

print(
    "RESULT:",
    OUT_CSV
)

print("=" * 78)

==============================================================================
122B IMAGE-ONLY 1000 SMOKE TEST
==============================================================================
SAMPLES : 1000
OUTPUT  : /content/drive/MyDrive/cleaning_data/122b_eval/122b_image_only_1000.csv
RESUME  : 0 / 1000
[0001/1000] train_0001.jpg | PRED=a GT=a ✅ | ACC=1/1=1.0000 | 2.58s
[0002/1000] train_0002.jpg | PRED=a GT=a ✅ | ACC=2/2=1.0000 | 1.23s
[0003/1000] train_0003.jpg | PRED=d GT=d ✅ | ACC=3/3=1.0000 | 1.22s
[0004/1000] train_0004.jpg | PRED=a GT=a ✅ | ACC=4/4=1.0000 | 1.24s
[0005/1000] train_0006.jpg | PRED=b GT=b ✅ | ACC=5/5=1.0000 | 1.24s
[0006/1000] train_0007.jpg | PRED=b GT=b ✅ | ACC=6/6=1.0000 | 1.23s
[0007/1000] train_0008.jpg | PRED=d GT=d ✅ | ACC=7/7=1.0000 | 1.24s
[0008/1000] train_0009.jpg | PRED=b GT=b ✅ | ACC=8/8=1.0000 | 1.23s
[0009/1000] train_0010.jpg | PRED=d GT=d ✅ | ACC=9/9=1.0000 | 1.24s
[0010/1000] train_0011.jpg | PRED=b GT=b ✅ | ACC=10/10=1.0000 | 1.22s
[0011/1000] train_0012.jpg | PRED=c GT=c ✅ | ACC=11/11=1.0000 | 1.22s
[0012/1000] train_0013.jpg | PRED=c GT=c ✅ | ACC=12/12=1.0000 | 1.23s
[0013/1000] train_0014.jpg | PRED=b GT=b ✅ | ACC=13/13=1.0000 | 1.22s
[0014/1000] train_0015.jpg | PRED=c GT=c ✅ | ACC=14/14=1.0000 | 1.22s
[0015/1000] train_0016.jpg | PRED=a GT=a ✅ | ACC=15/15=1.0000 | 1.22s
[0016/1000] train_0018.jpg | PRED=c GT=c ✅ | ACC=16/16=1.0000 | 1.23s
[0017/1000] train_0019.jpg | PRED=c GT=c ✅ | ACC=17/17=1.0000 | 1.34s
[0018/1000] train_0020.jpg | PRED=b GT=b ✅ | ACC=18/18=1.0000 | 1.36s
[0019/1000] train_0021.jpg | PRED=b GT=b ✅ | ACC=19/19=1.0000 | 1.24s
[0020/1000] train_0022.jpg | PRED=c GT=c ✅ | ACC=20/20=1.0000 | 1.50s
[0021/1000] train_0023.jpg | PRED=c GT=c ✅ | ACC=21/21=1.0000 | 1.23s
[0022/1000] train_0024.jpg | PRED=c GT=c ✅ | ACC=22/22=1.0000 | 1.22s
[0023/1000] train_0025.jpg | PRED=d GT=d ✅ | ACC=23/23=1.0000 | 1.22s
[0024/1000] train_0026.jpg | PRED=c GT=c ✅ | ACC=24/24=1.0000 | 1.32s
[0025/1000] train_0027.jpg | PRED=c GT=c ✅ | ACC=25/25=1.0000 | 1.24s
[0026/1000] train_0028.jpg | PRED=b GT=b ✅ | ACC=26/26=1.0000 | 1.33s
[0027/1000] train_0029.jpg | PRED=c GT=c ✅ | ACC=27/27=1.0000 | 1.22s
[0028/1000] train_0030.jpg | PRED=c GT=c ✅ | ACC=28/28=1.0000 | 1.15s
[0029/1000] train_0031.jpg | PRED=b GT=b ✅ | ACC=29/29=1.0000 | 1.23s
[0030/1000] train_0032.jpg | PRED=d GT=d ✅ | ACC=30/30=1.0000 | 1.23s
[0031/1000] train_0033.jpg | PRED=a GT=a ✅ | ACC=31/31=1.0000 | 1.23s
[0032/1000] train_0035.jpg | PRED=b GT=b ✅ | ACC=32/32=1.0000 | 1.21s
[0033/1000] train_0037.jpg | PRED=a GT=a ✅ | ACC=33/33=1.0000 | 1.14s
[0034/1000] train_0038.jpg | PRED=b GT=b ✅ | ACC=34/34=1.0000 | 1.23s
[0035/1000] train_0039.jpg | PRED=a GT=a ✅ | ACC=35/35=1.0000 | 1.47s
[0036/1000] train_0040.jpg | PRED=d GT=d ✅ | ACC=36/36=1.0000 | 1.22s
[0037/1000] train_0041.jpg | PRED=c GT=c ✅ | ACC=37/37=1.0000 | 1.22s
[0038/1000] train_0042.jpg | PRED=c GT=c ✅ | ACC=38/38=1.0000 | 1.23s
[0039/1000] train_0044.jpg | PRED=b GT=b ✅ | ACC=39/39=1.0000 | 1.24s
[0040/1000] train_0045.jpg | PRED=b GT=b ✅ | ACC=40/40=1.0000 | 1.22s
[0041/1000] train_0048.jpg | PRED=c GT=c ✅ | ACC=41/41=1.0000 | 1.15s
[0042/1000] train_0049.jpg | PRED=c GT=c ✅ | ACC=42/42=1.0000 | 1.23s
[0043/1000] train_0050.jpg | PRED=d GT=d ✅ | ACC=43/43=1.0000 | 1.23s
[0044/1000] train_0051.jpg | PRED=a GT=a ✅ | ACC=44/44=1.0000 | 1.23s
[0045/1000] train_0052.jpg | PRED=a GT=a ✅ | ACC=45/45=1.0000 | 1.23s
[0046/1000] train_0053.jpg | PRED=b GT=b ✅ | ACC=46/46=1.0000 | 1.24s
[0047/1000] train_0054.jpg | PRED=c GT=c ✅ | ACC=47/47=1.0000 | 1.23s
[0048/1000] train_0056.jpg | PRED=c GT=c ✅ | ACC=48/48=1.0000 | 1.32s
[0049/1000] train_0057.jpg | PRED=b GT=b ✅ | ACC=49/49=1.0000 | 1.22s
[0050/1000] train_0058.jpg | PRED=c GT=c ✅ | ACC=50/50=1.0000 | 1.31s
[0051/1000] train_0059.jpg | PRED=a GT=a ✅ | ACC=51/51=1.0000 | 1.22s
[0052/1000] train_0060.jpg | PRED=d GT=d ✅ | ACC=52/52=1.0000 | 1.23s
[0053/1000] train_0061.jpg | PRED=b GT=b ✅ | ACC=53/53=1.0000 | 1.22s
[0054/1000] train_0063.jpg | PRED=d GT=d ✅ | ACC=54/54=1.0000 | 1.44s
[0055/1000] train_0064.jpg | PRED=d GT=d ✅ | ACC=55/55=1.0000 | 1.23s
[0056/1000] train_0065.jpg | PRED=b GT=b ✅ | ACC=56/56=1.0000 | 1.21s
[0057/1000] train_0067.jpg | PRED=a GT=a ✅ | ACC=57/57=1.0000 | 1.22s
[0058/1000] train_0068.jpg | PRED=c GT=c ✅ | ACC=58/58=1.0000 | 1.23s
[0059/1000] train_0069.jpg | PRED=d GT=d ✅ | ACC=59/59=1.0000 | 1.24s
[0060/1000] train_0070.jpg | PRED=c GT=c ✅ | ACC=60/60=1.0000 | 1.23s
[0061/1000] train_0071.jpg | PRED=d GT=d ✅ | ACC=61/61=1.0000 | 1.23s
[0062/1000] train_0072.jpg | PRED=d GT=d ✅ | ACC=62/62=1.0000 | 1.24s
[0063/1000] train_0073.jpg | PRED=a GT=a ✅ | ACC=63/63=1.0000 | 1.20s
[0064/1000] train_0074.jpg | PRED=b GT=b ✅ | ACC=64/64=1.0000 | 1.21s
[0065/1000] train_0075.jpg | PRED=d GT=b ❌ | ACC=64/65=0.9846 | 1.24s
[0066/1000] train_0076.jpg | PRED=b GT=b ✅ | ACC=65/66=0.9848 | 1.22s
[0067/1000] train_0077.jpg | PRED=c GT=c ✅ | ACC=66/67=0.9851 | 1.22s
[0068/1000] train_0078.jpg | PRED=a GT=a ✅ | ACC=67/68=0.9853 | 1.22s
[0069/1000] train_0079.jpg | PRED=a GT=a ✅ | ACC=68/69=0.9855 | 1.42s
[0070/1000] train_0080.jpg | PRED=d GT=d ✅ | ACC=69/70=0.9857 | 1.24s
[0071/1000] train_0081.jpg | PRED=b GT=b ✅ | ACC=70/71=0.9859 | 1.23s
[0072/1000] train_0083.jpg | PRED=b GT=b ✅ | ACC=71/72=0.9861 | 1.21s
[0073/1000] train_0084.jpg | PRED=d GT=d ✅ | ACC=72/73=0.9863 | 1.23s
[0074/1000] train_0085.jpg | PRED=a GT=a ✅ | ACC=73/74=0.9865 | 1.23s
[0075/1000] train_0086.jpg | PRED=d GT=d ✅ | ACC=74/75=0.9867 | 1.23s
[0076/1000] train_0089.jpg | PRED=d GT=d ✅ | ACC=75/76=0.9868 | 1.21s
[0077/1000] train_0090.jpg | PRED=a GT=a ✅ | ACC=76/77=0.9870 | 1.30s
[0078/1000] train_0091.jpg | PRED=b GT=b ✅ | ACC=77/78=0.9872 | 1.22s
[0079/1000] train_0093.jpg | PRED=b GT=b ✅ | ACC=78/79=0.9873 | 1.14s
[0080/1000] train_0094.jpg | PRED=d GT=d ✅ | ACC=79/80=0.9875 | 1.21s
[0081/1000] train_0096.jpg | PRED=b GT=b ✅ | ACC=80/81=0.9877 | 1.34s
[0082/1000] train_0097.jpg | PRED=c GT=c ✅ | ACC=81/82=0.9878 | 1.25s
[0083/1000] train_0098.jpg | PRED=b GT=b ✅ | ACC=82/83=0.9880 | 1.25s
[0084/1000] train_0101.jpg | PRED=b GT=b ✅ | ACC=83/84=0.9881 | 1.21s
[0085/1000] train_0102.jpg | PRED=b GT=b ✅ | ACC=84/85=0.9882 | 1.23s
[0086/1000] train_0103.jpg | PRED=c GT=c ✅ | ACC=85/86=0.9884 | 1.25s
[0087/1000] train_0104.jpg | PRED=b GT=b ✅ | ACC=86/87=0.9885 | 1.23s
[0088/1000] train_0105.jpg | PRED=c GT=c ✅ | ACC=87/88=0.9886 | 1.22s
[0089/1000] train_0106.jpg | PRED=c GT=c ✅ | ACC=88/89=0.9888 | 1.24s
[0090/1000] train_0107.jpg | PRED=a GT=a ✅ | ACC=89/90=0.9889 | 1.22s
[0091/1000] train_0108.jpg | PRED=d GT=d ✅ | ACC=90/91=0.9890 | 1.22s
[0092/1000] train_0109.jpg | PRED=d GT=d ✅ | ACC=91/92=0.9891 | 1.24s
[0093/1000] train_0110.jpg | PRED=b GT=b ✅ | ACC=92/93=0.9892 | 1.32s
[0094/1000] train_0111.jpg | PRED=c GT=c ✅ | ACC=93/94=0.9894 | 1.22s
[0095/1000] train_0112.jpg | PRED=c GT=c ✅ | ACC=94/95=0.9895 | 1.24s
[0096/1000] train_0113.jpg | PRED=b GT=b ✅ | ACC=95/96=0.9896 | 1.23s
[0097/1000] train_0115.jpg | PRED=a GT=a ✅ | ACC=96/97=0.9897 | 1.24s
[0098/1000] train_0116.jpg | PRED=d GT=d ✅ | ACC=97/98=0.9898 | 1.26s
[0099/1000] train_0117.jpg | PRED=d GT=d ✅ | ACC=98/99=0.9899 | 1.23s
[0100/1000] train_0118.jpg | PRED=c GT=c ✅ | ACC=99/100=0.9900 | 1.23s
[0101/1000] train_0119.jpg | PRED=c GT=c ✅ | ACC=100/101=0.9901 | 1.23s
[0102/1000] train_0120.jpg | PRED=b GT=b ✅ | ACC=101/102=0.9902 | 1.32s
[0103/1000] train_0121.jpg | PRED=d GT=d ✅ | ACC=102/103=0.9903 | 1.21s
[0104/1000] train_0122.jpg | PRED=b GT=b ✅ | ACC=103/104=0.9904 | 1.25s
[0105/1000] train_0123.jpg | PRED=b GT=b ✅ | ACC=104/105=0.9905 | 1.23s
[0106/1000] train_0124.jpg | PRED=c GT=c ✅ | ACC=105/106=0.9906 | 1.14s
[0107/1000] train_0125.jpg | PRED=d GT=d ✅ | ACC=106/107=0.9907 | 1.24s
[0108/1000] train_0126.jpg | PRED=c GT=c ✅ | ACC=107/108=0.9907 | 1.42s
[0109/1000] train_0128.jpg | PRED=a GT=a ✅ | ACC=108/109=0.9908 | 1.23s
[0110/1000] train_0129.jpg | PRED=d GT=d ✅ | ACC=109/110=0.9909 | 1.36s
[0111/1000] train_0130.jpg | PRED=b GT=b ✅ | ACC=110/111=0.9910 | 1.34s
[0112/1000] train_0131.jpg | PRED=c GT=c ✅ | ACC=111/112=0.9911 | 1.23s
[0113/1000] train_0132.jpg | PRED=c GT=c ✅ | ACC=112/113=0.9912 | 1.33s
[0114/1000] train_0133.jpg | PRED=d GT=d ✅ | ACC=113/114=0.9912 | 1.21s
[0115/1000] train_0134.jpg | PRED=b GT=b ✅ | ACC=114/115=0.9913 | 1.25s
[0116/1000] train_0135.jpg | PRED=a GT=a ✅ | ACC=115/116=0.9914 | 1.24s
[0117/1000] train_0136.jpg | PRED=b GT=b ✅ | ACC=116/117=0.9915 | 1.24s
[0118/1000] train_0137.jpg | PRED=b GT=b ✅ | ACC=117/118=0.9915 | 1.24s
[0119/1000] train_0138.jpg | PRED=c GT=c ✅ | ACC=118/119=0.9916 | 1.22s
[0120/1000] train_0139.jpg | PRED=c GT=c ✅ | ACC=119/120=0.9917 | 1.22s
[0121/1000] train_0140.jpg | PRED=a GT=a ✅ | ACC=120/121=0.9917 | 1.23s
[0122/1000] train_0141.jpg | PRED=c GT=c ✅ | ACC=121/122=0.9918 | 1.20s
[0123/1000] train_0142.jpg | PRED=d GT=d ✅ | ACC=122/123=0.9919 | 1.22s
[0124/1000] train_0144.jpg | PRED=c GT=c ✅ | ACC=123/124=0.9919 | 1.24s
[0125/1000] train_0145.jpg | PRED=d GT=d ✅ | ACC=124/125=0.9920 | 1.22s
[0126/1000] train_0146.jpg | PRED=c GT=c ✅ | ACC=125/126=0.9921 | 1.23s
[0127/1000] train_0147.jpg | PRED=b GT=b ✅ | ACC=126/127=0.9921 | 1.24s
[0128/1000] train_0149.jpg | PRED=c GT=c ✅ | ACC=127/128=0.9922 | 1.23s
[0129/1000] train_0150.jpg | PRED=d GT=d ✅ | ACC=128/129=0.9922 | 1.22s
[0130/1000] train_0151.jpg | PRED=a GT=a ✅ | ACC=129/130=0.9923 | 1.22s
[0131/1000] train_0152.jpg | PRED=b GT=b ✅ | ACC=130/131=0.9924 | 1.24s
[0132/1000] train_0153.jpg | PRED=a GT=a ✅ | ACC=131/132=0.9924 | 1.24s
[0133/1000] train_0154.jpg | PRED=c GT=c ✅ | ACC=132/133=0.9925 | 1.23s
[0134/1000] train_0155.jpg | PRED=a GT=a ✅ | ACC=133/134=0.9925 | 1.23s
[0135/1000] train_0156.jpg | PRED=a GT=a ✅ | ACC=134/135=0.9926 | 1.24s
[0136/1000] train_0157.jpg | PRED=a GT=a ✅ | ACC=135/136=0.9926 | 1.22s
[0137/1000] train_0158.jpg | PRED=a GT=a ✅ | ACC=136/137=0.9927 | 1.25s
[0138/1000] train_0159.jpg | PRED=d GT=d ✅ | ACC=137/138=0.9928 | 1.23s
[0139/1000] train_0160.jpg | PRED=a GT=a ✅ | ACC=138/139=0.9928 | 1.24s
[0140/1000] train_0161.jpg | PRED=c GT=c ✅ | ACC=139/140=0.9929 | 1.24s
[0141/1000] train_0162.jpg | PRED=b GT=b ✅ | ACC=140/141=0.9929 | 1.22s
[0142/1000] train_0163.jpg | PRED=a GT=a ✅ | ACC=141/142=0.9930 | 1.26s
[0143/1000] train_0164.jpg | PRED=d GT=d ✅ | ACC=142/143=0.9930 | 1.33s
[0144/1000] train_0165.jpg | PRED=b GT=b ✅ | ACC=143/144=0.9931 | 1.23s
[0145/1000] train_0166.jpg | PRED=c GT=c ✅ | ACC=144/145=0.9931 | 1.23s
[0146/1000] train_0167.jpg | PRED=b GT=b ✅ | ACC=145/146=0.9932 | 1.22s
[0147/1000] train_0168.jpg | PRED=a GT=a ✅ | ACC=146/147=0.9932 | 1.40s
[0148/1000] train_0170.jpg | PRED=c GT=c ✅ | ACC=147/148=0.9932 | 1.22s
[0149/1000] train_0171.jpg | PRED=c GT=c ✅ | ACC=148/149=0.9933 | 1.34s
[0150/1000] train_0172.jpg | PRED=d GT=d ✅ | ACC=149/150=0.9933 | 1.23s
[0151/1000] train_0173.jpg | PRED=a GT=a ✅ | ACC=150/151=0.9934 | 1.32s
[0152/1000] train_0174.jpg | PRED=c GT=c ✅ | ACC=151/152=0.9934 | 1.26s
[0153/1000] train_0176.jpg | PRED=a GT=a ✅ | ACC=152/153=0.9935 | 1.20s
[0154/1000] train_0178.jpg | PRED=d GT=d ✅ | ACC=153/154=0.9935 | 1.23s
[0155/1000] train_0179.jpg | PRED=c GT=c ✅ | ACC=154/155=0.9935 | 1.24s
[0156/1000] train_0180.jpg | PRED=b GT=b ✅ | ACC=155/156=0.9936 | 1.23s
[0157/1000] train_0183.jpg | PRED=c GT=c ✅ | ACC=156/157=0.9936 | 1.15s
[0158/1000] train_0185.jpg | PRED=c GT=c ✅ | ACC=157/158=0.9937 | 1.21s
[0159/1000] train_0186.jpg | PRED=b GT=b ✅ | ACC=158/159=0.9937 | 1.23s
[0160/1000] train_0187.jpg | PRED=d GT=d ✅ | ACC=159/160=0.9938 | 1.23s
[0161/1000] train_0188.jpg | PRED=a GT=a ✅ | ACC=160/161=0.9938 | 1.23s
[0162/1000] train_0189.jpg | PRED=d GT=d ✅ | ACC=161/162=0.9938 | 1.22s
[0163/1000] train_0190.jpg | PRED=d GT=d ✅ | ACC=162/163=0.9939 | 1.23s
[0164/1000] train_0191.jpg | PRED=c GT=c ✅ | ACC=163/164=0.9939 | 1.23s
[0165/1000] train_0192.jpg | PRED=c GT=c ✅ | ACC=164/165=0.9939 | 1.22s
[0166/1000] train_0193.jpg | PRED=d GT=d ✅ | ACC=165/166=0.9940 | 1.23s
[0167/1000] train_0194.jpg | PRED=c GT=c ✅ | ACC=166/167=0.9940 | 1.23s
[0168/1000] train_0195.jpg | PRED=c GT=c ✅ | ACC=167/168=0.9940 | 1.17s
[0169/1000] train_0197.jpg | PRED=a GT=a ✅ | ACC=168/169=0.9941 | 1.32s
[0170/1000] train_0198.jpg | PRED=c GT=c ✅ | ACC=169/170=0.9941 | 1.21s
[0171/1000] train_0200.jpg | PRED=c GT=c ✅ | ACC=170/171=0.9942 | 1.22s
[0172/1000] train_0203.jpg | PRED=c GT=c ✅ | ACC=171/172=0.9942 | 1.23s
[0173/1000] train_0206.jpg | PRED=c GT=c ✅ | ACC=172/173=0.9942 | 1.22s
[0174/1000] train_0207.jpg | PRED=c GT=a ❌ | ACC=172/174=0.9885 | 1.15s
[0175/1000] train_0208.jpg | PRED=d GT=d ✅ | ACC=173/175=0.9886 | 1.24s
[0176/1000] train_0209.jpg | PRED=d GT=b ❌ | ACC=173/176=0.9830 | 1.24s
[0177/1000] train_0210.jpg | PRED=a GT=a ✅ | ACC=174/177=0.9831 | 1.23s
[0178/1000] train_0211.jpg | PRED=c GT=c ✅ | ACC=175/178=0.9831 | 1.24s
[0179/1000] train_0212.jpg | PRED=a GT=a ✅ | ACC=176/179=0.9832 | 1.23s
[0180/1000] train_0213.jpg | PRED=d GT=d ✅ | ACC=177/180=0.9833 | 1.23s
[0181/1000] train_0214.jpg | PRED=a GT=a ✅ | ACC=178/181=0.9834 | 1.23s
[0182/1000] train_0216.jpg | PRED=c GT=c ✅ | ACC=179/182=0.9835 | 1.14s
[0183/1000] train_0217.jpg | PRED=c GT=c ✅ | ACC=180/183=0.9836 | 1.23s
[0184/1000] train_0218.jpg | PRED=a GT=a ✅ | ACC=181/184=0.9837 | 1.23s
[0185/1000] train_0220.jpg | PRED=c GT=c ✅ | ACC=182/185=0.9838 | 1.24s
[0186/1000] train_0221.jpg | PRED=a GT=a ✅ | ACC=183/186=0.9839 | 1.22s
[0187/1000] train_0222.jpg | PRED=a GT=a ✅ | ACC=184/187=0.9840 | 1.16s
[0188/1000] train_0223.jpg | PRED=d GT=d ✅ | ACC=185/188=0.9840 | 1.23s
[0189/1000] train_0224.jpg | PRED=b GT=b ✅ | ACC=186/189=0.9841 | 1.22s
[0190/1000] train_0225.jpg | PRED=d GT=d ✅ | ACC=187/190=0.9842 | 1.23s
[0191/1000] train_0226.jpg | PRED=b GT=b ✅ | ACC=188/191=0.9843 | 1.66s
[0192/1000] train_0227.jpg | PRED=b GT=b ✅ | ACC=189/192=0.9844 | 1.23s
[0193/1000] train_0228.jpg | PRED=b GT=b ✅ | ACC=190/193=0.9845 | 1.23s
[0194/1000] train_0229.jpg | PRED=d GT=d ✅ | ACC=191/194=0.9845 | 1.23s
[0195/1000] train_0230.jpg | PRED=a GT=a ✅ | ACC=192/195=0.9846 | 1.24s
[0196/1000] train_0233.jpg | PRED=b GT=b ✅ | ACC=193/196=0.9847 | 1.23s
[0197/1000] train_0234.jpg | PRED=c GT=c ✅ | ACC=194/197=0.9848 | 1.34s
[0198/1000] train_0235.jpg | PRED=b GT=b ✅ | ACC=195/198=0.9848 | 1.25s
[0199/1000] train_0238.jpg | PRED=b GT=b ✅ | ACC=196/199=0.9849 | 1.44s
[0200/1000] train_0239.jpg | PRED=d GT=d ✅ | ACC=197/200=0.9850 | 1.23s
[0201/1000] train_0240.jpg | PRED=d GT=d ✅ | ACC=198/201=0.9851 | 1.23s
[0202/1000] train_0241.jpg | PRED=d GT=d ✅ | ACC=199/202=0.9851 | 1.26s
[0203/1000] train_0242.jpg | PRED=a GT=a ✅ | ACC=200/203=0.9852 | 1.23s
[0204/1000] train_0243.jpg | PRED=d GT=d ✅ | ACC=201/204=0.9853 | 1.23s
[0205/1000] train_0244.jpg | PRED=c GT=c ✅ | ACC=202/205=0.9854 | 1.23s
[0206/1000] train_0247.jpg | PRED=d GT=d ✅ | ACC=203/206=0.9854 | 1.24s
[0207/1000] train_0248.jpg | PRED=a GT=a ✅ | ACC=204/207=0.9855 | 1.24s
[0208/1000] train_0249.jpg | PRED=d GT=d ✅ | ACC=205/208=0.9856 | 1.24s
[0209/1000] train_0251.jpg | PRED=c GT=c ✅ | ACC=206/209=0.9856 | 1.22s
[0210/1000] train_0252.jpg | PRED=c GT=c ✅ | ACC=207/210=0.9857 | 1.26s
[0211/1000] train_0253.jpg | PRED=d GT=d ✅ | ACC=208/211=0.9858 | 1.25s
[0212/1000] train_0254.jpg | PRED=d GT=d ✅ | ACC=209/212=0.9858 | 1.32s
[0213/1000] train_0255.jpg | PRED=d GT=d ✅ | ACC=210/213=0.9859 | 1.23s
[0214/1000] train_0256.jpg | PRED=d GT=d ✅ | ACC=211/214=0.9860 | 1.22s
[0215/1000] train_0257.jpg | PRED=c GT=c ✅ | ACC=212/215=0.9860 | 1.33s
[0216/1000] train_0258.jpg | PRED=b GT=b ✅ | ACC=213/216=0.9861 | 1.35s
[0217/1000] train_0259.jpg | PRED=c GT=c ✅ | ACC=214/217=0.9862 | 1.36s
[0218/1000] train_0260.jpg | PRED=b GT=b ✅ | ACC=215/218=0.9862 | 1.24s
[0219/1000] train_0261.jpg | PRED=c GT=c ✅ | ACC=216/219=0.9863 | 1.22s
[0220/1000] train_0262.jpg | PRED=a GT=a ✅ | ACC=217/220=0.9864 | 1.22s
[0221/1000] train_0263.jpg | PRED=a GT=a ✅ | ACC=218/221=0.9864 | 1.22s
[0222/1000] train_0264.jpg | PRED=d GT=d ✅ | ACC=219/222=0.9865 | 1.24s
[0223/1000] train_0265.jpg | PRED=a GT=a ✅ | ACC=220/223=0.9865 | 1.18s
[0224/1000] train_0266.jpg | PRED=d GT=d ✅ | ACC=221/224=0.9866 | 1.22s
[0225/1000] train_0267.jpg | PRED=b GT=b ✅ | ACC=222/225=0.9867 | 1.22s
[0226/1000] train_0268.jpg | PRED=c GT=c ✅ | ACC=223/226=0.9867 | 1.22s
[0227/1000] train_0269.jpg | PRED=a GT=a ✅ | ACC=224/227=0.9868 | 1.23s
[0228/1000] train_0270.jpg | PRED=a GT=a ✅ | ACC=225/228=0.9868 | 1.24s
[0229/1000] train_0271.jpg | PRED=a GT=a ✅ | ACC=226/229=0.9869 | 1.24s
[0230/1000] train_0272.jpg | PRED=c GT=c ✅ | ACC=227/230=0.9870 | 1.24s
[0231/1000] train_0273.jpg | PRED=d GT=d ✅ | ACC=228/231=0.9870 | 1.22s
[0232/1000] train_0276.jpg | PRED=b GT=b ✅ | ACC=229/232=0.9871 | 1.22s
[0233/1000] train_0277.jpg | PRED=c GT=c ✅ | ACC=230/233=0.9871 | 1.22s
[0234/1000] train_0279.jpg | PRED=b GT=b ✅ | ACC=231/234=0.9872 | 1.22s
[0235/1000] train_0280.jpg | PRED=c GT=c ✅ | ACC=232/235=0.9872 | 1.18s
[0236/1000] train_0281.jpg | PRED=d GT=d ✅ | ACC=233/236=0.9873 | 1.25s
[0237/1000] train_0282.jpg | PRED=b GT=b ✅ | ACC=234/237=0.9873 | 1.23s
[0238/1000] train_0283.jpg | PRED=c GT=c ✅ | ACC=235/238=0.9874 | 1.15s
[0239/1000] train_0284.jpg | PRED=b GT=b ✅ | ACC=236/239=0.9874 | 1.35s
[0240/1000] train_0286.jpg | PRED=b GT=b ✅ | ACC=237/240=0.9875 | 1.21s
[0241/1000] train_0287.jpg | PRED=a GT=a ✅ | ACC=238/241=0.9876 | 1.36s
[0242/1000] train_0288.jpg | PRED=b GT=b ✅ | ACC=239/242=0.9876 | 1.32s
[0243/1000] train_0289.jpg | PRED=a GT=a ✅ | ACC=240/243=0.9877 | 1.23s
[0244/1000] train_0290.jpg | PRED=b GT=b ✅ | ACC=241/244=0.9877 | 1.21s
[0245/1000] train_0293.jpg | PRED=d GT=d ✅ | ACC=242/245=0.9878 | 1.22s
[0246/1000] train_0294.jpg | PRED=b GT=b ✅ | ACC=243/246=0.9878 | 1.23s
[0247/1000] train_0295.jpg | PRED=b GT=b ✅ | ACC=244/247=0.9879 | 1.23s
[0248/1000] train_0296.jpg | PRED=b GT=b ✅ | ACC=245/248=0.9879 | 1.23s
[0249/1000] train_0297.jpg | PRED=b GT=b ✅ | ACC=246/249=0.9880 | 1.22s
[0250/1000] train_0298.jpg | PRED=b GT=b ✅ | ACC=247/250=0.9880 | 1.23s
[0251/1000] train_0299.jpg | PRED=b GT=b ✅ | ACC=248/251=0.9880 | 1.23s
[0252/1000] train_0300.jpg | PRED=a GT=a ✅ | ACC=249/252=0.9881 | 1.23s
[0253/1000] train_0301.jpg | PRED=b GT=b ✅ | ACC=250/253=0.9881 | 1.22s
[0254/1000] train_0302.jpg | PRED=a GT=a ✅ | ACC=251/254=0.9882 | 1.21s
[0255/1000] train_0303.jpg | PRED=b GT=b ✅ | ACC=252/255=0.9882 | 1.21s
[0256/1000] train_0304.jpg | PRED=a GT=a ✅ | ACC=253/256=0.9883 | 1.26s
[0257/1000] train_0305.jpg | PRED=d GT=d ✅ | ACC=254/257=0.9883 | 1.14s
[0258/1000] train_0306.jpg | PRED=c GT=c ✅ | ACC=255/258=0.9884 | 1.20s
[0259/1000] train_0307.jpg | PRED=c GT=c ✅ | ACC=256/259=0.9884 | 1.23s
[0260/1000] train_0308.jpg | PRED=d GT=d ✅ | ACC=257/260=0.9885 | 1.24s
[0261/1000] train_0309.jpg | PRED=a GT=a ✅ | ACC=258/261=0.9885 | 1.27s
[0262/1000] train_0310.jpg | PRED=a GT=a ✅ | ACC=259/262=0.9885 | 1.23s
[0263/1000] train_0311.jpg | PRED=b GT=b ✅ | ACC=260/263=0.9886 | 1.32s
[0264/1000] train_0312.jpg | PRED=a GT=a ✅ | ACC=261/264=0.9886 | 1.25s
[0265/1000] train_0313.jpg | PRED=d GT=d ✅ | ACC=262/265=0.9887 | 1.21s
[0266/1000] train_0314.jpg | PRED=c GT=c ✅ | ACC=263/266=0.9887 | 1.24s
[0267/1000] train_0317.jpg | PRED=c GT=c ✅ | ACC=264/267=0.9888 | 1.24s
[0268/1000] train_0318.jpg | PRED=d GT=b ❌ | ACC=264/268=0.9851 | 1.21s
[0269/1000] train_0319.jpg | PRED=d GT=d ✅ | ACC=265/269=0.9851 | 1.22s
[0270/1000] train_0320.jpg | PRED=a GT=a ✅ | ACC=266/270=0.9852 | 1.22s
[0271/1000] train_0321.jpg | PRED=d GT=d ✅ | ACC=267/271=0.9852 | 1.33s
[0272/1000] train_0322.jpg | PRED=d GT=d ✅ | ACC=268/272=0.9853 | 1.26s
[0273/1000] train_0324.jpg | PRED=c GT=c ✅ | ACC=269/273=0.9853 | 1.23s
[0274/1000] train_0325.jpg | PRED=d GT=d ✅ | ACC=270/274=0.9854 | 1.22s
[0275/1000] train_0326.jpg | PRED=a GT=a ✅ | ACC=271/275=0.9855 | 1.27s
[0276/1000] train_0327.jpg | PRED=c GT=c ✅ | ACC=272/276=0.9855 | 1.23s

# Step 3. Test 전체 추론 및 Submission 생성

Step 2에서 검증한 Qwen3.5-122B Image-only 설정을 그대로 사용하여
대회 Test 데이터 전체를 추론한다.

검증 단계에서 사용한 다음 설정은 변경하지 않는다.

- 실제 이미지 + 질문 + 선택지 a / b / c / d
- OCR 사용하지 않음
- Object Detection 사용하지 않음
- enable_thinking=False
- temperature=0.0
- structured output: a / b / c / d
- max_tokens=2

Test 추론 결과는 중간 저장하여 런타임 오류가 발생하더라도
완료된 문제부터 이어서 실행할 수 있도록 한다.

전체 추론 완료 후 대회 제출 형식인

- id
- answer

두 컬럼으로 Submission CSV를 생성한다.

In [10]:
# ============================================================
# [STEP 3-0] TEST DATA VERIFY
#
# 추론 전에:
# - test.csv 확인
# - sample_submission.csv 확인
# - 필수 컬럼 확인
# - 모든 test 이미지 존재 확인
#
# 아직 모델 추론은 수행하지 않음
# ============================================================

from pathlib import Path

import pandas as pd


# ============================================================
# 0. MODEL / STEP 2 OBJECT CHECK
# ============================================================

assert (
    "llm_122b" in globals()
    and llm_122b is not None
), "❌ Step 1 모델 로드부터 필요합니다."


assert "DATA_ROOT" in globals(), (
    "❌ DATA_ROOT가 없습니다."
)


assert "SYSTEM_PROMPT" in globals(), (
    "❌ Step 2 SYSTEM_PROMPT가 없습니다."
)


assert "build_image_only_prompt" in globals(), (
    "❌ Step 2 build_image_only_prompt가 없습니다."
)


assert "sampling_params_image_only" in globals(), (
    "❌ Step 2 sampling_params_image_only가 없습니다."
)


# ============================================================
# 1. PATH
# ============================================================

TEST_CSV = (
    DATA_ROOT
    / "test.csv"
)

SAMPLE_SUBMISSION_CSV = (
    DATA_ROOT
    / "sample_submission.csv"
)


assert TEST_CSV.exists(), (
    f"❌ test.csv 없음: {TEST_CSV}"
)

assert SAMPLE_SUBMISSION_CSV.exists(), (
    f"❌ sample_submission.csv 없음: {SAMPLE_SUBMISSION_CSV}"
)


# ============================================================
# 2. LOAD
# ============================================================

test_df = pd.read_csv(
    TEST_CSV
)

sample_submission = pd.read_csv(
    SAMPLE_SUBMISSION_CSV
)


# ============================================================
# 3. COLUMN CHECK
# ============================================================

required_test_cols = [
    "id",
    "path",
    "question",
    "a",
    "b",
    "c",
    "d",
]


missing = [
    c
    for c in required_test_cols
    if c not in test_df.columns
]


assert not missing, (
    f"❌ test.csv 컬럼 누락: {missing}"
)


assert "id" in sample_submission.columns, (
    "❌ sample_submission.csv에 id 컬럼 없음"
)


assert "answer" in sample_submission.columns, (
    "❌ sample_submission.csv에 answer 컬럼 없음"
)


# ============================================================
# 4. ID / ROW CHECK
# ============================================================

assert len(test_df) == len(sample_submission), (
    "❌ test / sample_submission 행 수 불일치: "
    f"{len(test_df)} vs {len(sample_submission)}"
)


assert (
    test_df["id"]
    .astype(str)
    .tolist()
    ==
    sample_submission["id"]
    .astype(str)
    .tolist()
), "❌ test와 sample_submission의 id 순서가 다릅니다."


# ============================================================
# 5. IMAGE CHECK
# ============================================================

image_exists = test_df["path"].map(
    lambda p:
    (DATA_ROOT / str(p)).exists()
)


missing_images = test_df.loc[
    ~image_exists,
    [
        "id",
        "path",
    ]
]


# ============================================================
# 6. RESULT
# ============================================================

print("=" * 78)
print("STEP 3-0 : TEST DATA VERIFY")
print("=" * 78)

print(
    "DATA_ROOT          :",
    DATA_ROOT
)

print(
    "TEST CSV           :",
    TEST_CSV
)

print(
    "TEST ROWS          :",
    len(test_df)
)

print(
    "TEST COLUMNS       :",
    test_df.columns.tolist()
)

print(
    "SUBMISSION ROWS    :",
    len(sample_submission)
)

print(
    "SUBMISSION COLUMNS :",
    sample_submission.columns.tolist()
)

print(
    "IMAGES             :",
    int(image_exists.sum()),
    "/",
    len(test_df)
)

print("=" * 78)


if len(missing_images) > 0:

    print("\n❌ 누락 이미지:")
    display(
        missing_images.head(20)
    )

else:

    print(
        "\n✅ TEST DATA READY"
    )


display(
    test_df.head(3)
)

display(
    sample_submission.head(3)
)

==============================================================================
STEP 3-0 : TEST DATA VERIFY
==============================================================================
DATA_ROOT          : /content/ssafy_data
TEST CSV           : /content/ssafy_data/test.csv
TEST ROWS          : 6714
TEST COLUMNS       : ['id', 'path', 'question', 'a', 'b', 'c', 'd']
SUBMISSION ROWS    : 6714
SUBMISSION COLUMNS : ['id', 'answer']
IMAGES             : 6714 / 6714
==============================================================================

✅ TEST DATA READY

,id,path,question,a,b,c,d
0,test_0001.jpg,test/test_0001.jpg,이 사진 속 간판 중에서 '머리염색 체험방'이 적혀 있는 간판의 전화번호는 무엇인가요?,010-1234-5678,722-7510,123-4567,732-3258
1,test_0002.jpg,test/test_0002.jpg,이 식당 간판에 적힌 전문점의 종류는 무엇인가요?,중식 전문점,해산물 전문점,소고기숯불구이 전문점,한식 전문점
2,test_0003.jpg,test/test_0003.jpg,이 사진에 보이는 IT대학 발전기금 현황판에서 IT대학 50주년 후원금 중 10억원...,SK hynix,LG,삼성전자,세 가지 모두

              id  answer
0  test_0001.jpg     NaN
1  test_0002.jpg     NaN
2  test_0003.jpg     NaN

In [11]:
# ============================================================
# [STEP 3-1] 122B IMAGE-ONLY TEST FULL INFERENCE
#
# Step 2에서 98.4%를 기록한 설정 그대로 사용
#
# 입력:
# - 실제 이미지
# - question
# - a / b / c / d
#
# 사용하지 않음:
# - OCR
# - DINO
# - GT
#
# 설정:
# - enable_thinking=False
# - temperature=0.0
# - structured output: a/b/c/d
# - max_tokens=2
#
# 기능:
# - 6714개 전체 Test 추론
# - 중간 저장
# - 런타임 중단 후 재실행 시 자동 Resume
# ============================================================

import os
import time
import inspect
import pandas as pd

from pathlib import Path
from PIL import Image


# ============================================================
# 0. CONFIG
# ============================================================

TEST_N = len(test_df)

TEST_OUT_DIR = Path(
    "/content/drive/MyDrive/"
    "cleaning_data/"
    "122b_eval"
)

TEST_OUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


TEST_OUT_CSV = (
    TEST_OUT_DIR
    / "122b_image_only_test.csv"
)


# ============================================================
# 1. OBJECT CHECK
# ============================================================

assert (
    "llm_122b" in globals()
    and llm_122b is not None
), "❌ llm_122b가 없습니다."


assert "SYSTEM_PROMPT" in globals(), (
    "❌ SYSTEM_PROMPT가 없습니다."
)


assert "build_image_only_prompt" in globals(), (
    "❌ build_image_only_prompt가 없습니다."
)


assert "sampling_params_image_only" in globals(), (
    "❌ sampling_params_image_only가 없습니다."
)


assert len(test_df) == 6714, (
    f"❌ 예상 Test 6714개, 실제 {len(test_df)}개"
)


print("=" * 78)
print("122B IMAGE-ONLY TEST FULL INFERENCE")
print("=" * 78)

print(
    "TEST SAMPLES :",
    TEST_N
)

print(
    "OUTPUT       :",
    TEST_OUT_CSV
)


# ============================================================
# 2. RESUME
# ============================================================

test_results = {}


if TEST_OUT_CSV.exists():

    old = pd.read_csv(
        TEST_OUT_CSV
    )

    print(
        "\n기존 결과:",
        len(old),
        "rows"
    )


    for rec in (
        old
        .drop_duplicates(
            "id",
            keep="last"
        )
        .to_dict("records")
    ):

        test_results[
            str(rec["id"])
        ] = rec


test_done_ids = {

    k

    for k, v
    in test_results.items()

    if str(
        v.get(
            "status",
            ""
        )
    ) == "ok"

    and str(
        v.get(
            "image_only_answer",
            ""
        )
    ).strip().lower()

    in {
        "a",
        "b",
        "c",
        "d",
    }
}


print(
    "RESUME       :",
    len(test_done_ids),
    "/",
    TEST_N
)


# ============================================================
# 3. SAVE FUNCTION
# ============================================================

def save_test_results():

    x = pd.DataFrame(
        list(
            test_results.values()
        )
    )


    if len(x) > 0:

        x = (
            x
            .sort_values("idx")
            .reset_index(drop=True)
        )


    tmp = Path(
        str(TEST_OUT_CSV)
        + ".tmp"
    )


    x.to_csv(
        tmp,
        index=False,
        encoding="utf-8-sig",
    )


    os.replace(
        tmp,
        TEST_OUT_CSV,
    )


# ============================================================
# 4. TQDM SUPPORT
# ============================================================

SUPPORTS_USE_TQDM = (
    "use_tqdm"
    in inspect.signature(
        llm_122b.chat
    ).parameters
)


# ============================================================
# 5. LOOP
# ============================================================

run_start = time.time()


for idx, row in test_df.iterrows():

    img_id = str(
        row["id"]
    )


    # 이미 정상 완료된 문제는 Skip
    if img_id in test_done_ids:
        continue


    image_path = (
        DATA_ROOT
        / str(
            row["path"]
        )
    )


    t0 = time.time()


    try:

        assert image_path.exists(), (
            f"이미지 없음: {image_path}"
        )


        with Image.open(
            image_path
        ) as im:

            image = (
                im
                .convert("RGB")
                .copy()
            )


        messages = [

            {
                "role":
                    "system",

                "content":
                    SYSTEM_PROMPT,
            },

            {
                "role":
                    "user",

                "content": [

                    {
                        "type":
                            "image_pil",

                        "image_pil":
                            image,
                    },

                    {
                        "type":
                            "text",

                        "text":
                            build_image_only_prompt(

                                row["question"],

                                row["a"],
                                row["b"],
                                row["c"],
                                row["d"],
                            ),
                    },
                ],
            },
        ]


        kwargs = dict(

            messages=
                messages,

            sampling_params=
                sampling_params_image_only,

            chat_template_kwargs={
                "enable_thinking":
                    False
            },
        )


        if SUPPORTS_USE_TQDM:

            kwargs[
                "use_tqdm"
            ] = False


        outputs = llm_122b.chat(
            **kwargs
        )


        pred = (
            outputs[0]
            .outputs[0]
            .text
            .strip()
            .lower()
        )


        assert pred in {
            "a",
            "b",
            "c",
            "d",
        }, (
            f"비정상 prediction: {repr(pred)}"
        )


        status = "ok"
        error = ""


    except Exception as e:

        pred = ""
        status = "error"
        error = repr(e)


    elapsed = (
        time.time()
        - t0
    )


    # ========================================================
    # RESULT
    # ========================================================

    test_results[
        img_id
    ] = {

        "idx":
            int(idx),

        "id":
            img_id,

        "path":
            row["path"],

        "image_only_answer":
            pred,

        "elapsed_sec":
            round(
                elapsed,
                4
            ),

        "status":
            status,

        "error":
            error,
    }


    if status == "ok":

        test_done_ids.add(
            img_id
        )


    # 매 문제 저장
    save_test_results()


    # ========================================================
    # PROGRESS
    # ========================================================

    done_n = len(
        test_done_ids
    )


    if status == "ok":

        mark = "✅"

    else:

        mark = "❌"


    print(

        f"[{done_n:04d}/{TEST_N}] "

        f"{img_id} | "

        f"PRED={pred} "

        f"{mark} | "

        f"{elapsed:.2f}s",

        flush=True,
    )


# ============================================================
# 6. FINAL CHECK
# ============================================================

final_test = pd.DataFrame(
    list(
        test_results.values()
    )
)


final_test = (
    final_test
    .sort_values("idx")
    .reset_index(drop=True)
)


ok_test = final_test[
    final_test["status"]
    == "ok"
]


error_test = final_test[
    final_test["status"]
    != "ok"
]


valid_answer = (
    ok_test[
        "image_only_answer"
    ]
    .astype(str)
    .str.lower()
    .isin(
        {
            "a",
            "b",
            "c",
            "d",
        }
    )
)


print("\n" + "=" * 78)

print(
    "122B TEST INFERENCE FINISHED"
)

print("=" * 78)

print(
    "TOTAL SAVED :",
    len(final_test)
)

print(
    "OK          :",
    len(ok_test)
)

print(
    "ERROR       :",
    len(error_test)
)

print(
    "VALID ANSWER:",
    int(valid_answer.sum()),
    "/",
    len(ok_test)
)

print(
    "RESULT      :",
    TEST_OUT_CSV
)

print("=" * 78)


if len(error_test) > 0:

    print(
        "\n⚠️ ERROR CASES"
    )

    display(
        error_test[
            [
                "idx",
                "id",
                "path",
                "error",
            ]
        ]
    )

else:

    print(
        "\n✅ ALL 6714 TEST SAMPLES COMPLETE"
    )


print(
    "\nANSWER DISTRIBUTION:"
)

print(
    ok_test[
        "image_only_answer"
    ]
    .value_counts()
    .sort_index()
)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
[1727/6714] test_1727.jpg | PRED=a ✅ | 1.23s
[1728/6714] test_1728.jpg | PRED=c ✅ | 1.22s
[1729/6714] test_1729.jpg | PRED=b ✅ | 1.32s
[1730/6714] test_1730.jpg | PRED=d ✅ | 1.21s
[1731/6714] test_1731.jpg | PRED=c ✅ | 1.23s
[1732/6714] test_1732.jpg | PRED=c ✅ | 1.22s
[1733/6714] test_1733.jpg | PRED=d ✅ | 1.23s
[1734/6714] test_1734.jpg | PRED=b ✅ | 1.22s
[1735/6714] test_1735.jpg | PRED=a ✅ | 1.23s
[1736/6714] test_1736.jpg | PRED=c ✅ | 1.33s
[1737/6714] test_1737.jpg | PRED=b ✅ | 1.24s
[1738/6714] test_1738.jpg | PRED=c ✅ | 1.22s
[1739/6714] test_1739.jpg | PRED=c ✅ | 1.22s
[1740/6714] test_1740.jpg | PRED=b ✅ | 1.22s
[1741/6714] test_1741.jpg | PRED=a ✅ | 1.23s
[1742/6714] test_1742.jpg | PRED=d ✅ | 1.23s
[1743/6714] test_1743.jpg | PRED=b ✅ | 1.23s
[1744/6714] test_1744.jpg | PRED=c ✅ | 1.23s
[1745/6714] test_1745.jpg | PRED=b ✅ | 1.22s
[1746/6714] test_1746.jpg | PRED=d ✅ | 1.21s
[1747/6714] test_1747.jpg | PRED=d ✅ | 1.23s
[1748/6714] test_1748.jpg | PRED=b ✅ | 1.31s
[1749/6714] test_1749.jpg | PRED=c ✅ | 1.24s
[1750/6714] test_1750.jpg | PRED=b ✅ | 1.23s
[1751/6714] test_1751.jpg | PRED=d ✅ | 1.25s
[1752/6714] test_1752.jpg | PRED=c ✅ | 1.24s
[1753/6714] test_1753.jpg | PRED=a ✅ | 1.25s
[1754/6714] test_1754.jpg | PRED=c ✅ | 1.15s
[1755/6714] test_1755.jpg | PRED=b ✅ | 1.26s
[1756/6714] test_1756.jpg | PRED=c ✅ | 1.24s
[1757/6714] test_1757.jpg | PRED=b ✅ | 1.22s
[1758/6714] test_1758.jpg | PRED=c ✅ | 1.23s
[1759/6714] test_1759.jpg | PRED=a ✅ | 1.22s
[1760/6714] test_1760.jpg | PRED=a ✅ | 1.23s
[1761/6714] test_1761.jpg | PRED=b ✅ | 1.22s
[1762/6714] test_1762.jpg | PRED=a ✅ | 1.24s
[1763/6714] test_1763.jpg | PRED=d ✅ | 1.22s
[1764/6714] test_1764.jpg | PRED=b ✅ | 1.24s
[1765/6714] test_1765.jpg | PRED=b ✅ | 1.23s
[1766/6714] test_1766.jpg | PRED=a ✅ | 1.23s
[1767/6714] test_1767.jpg | PRED=c ✅ | 1.22s
[1768/6714] test_1768.jpg | PRED=d ✅ | 1.22s
[1769/6714] test_1769.jpg | PRED=b ✅ | 1.23s
[1770/6714] test_1770.jpg | PRED=d ✅ | 1.24s
[1771/6714] test_1771.jpg | PRED=d ✅ | 1.26s
[1772/6714] test_1772.jpg | PRED=c ✅ | 1.23s
[1773/6714] test_1773.jpg | PRED=a ✅ | 1.24s
[1774/6714] test_1774.jpg | PRED=a ✅ | 1.34s
[1775/6714] test_1775.jpg | PRED=d ✅ | 1.22s
[1776/6714] test_1776.jpg | PRED=d ✅ | 1.23s
[1777/6714] test_1777.jpg | PRED=a ✅ | 1.22s
[1778/6714] test_1778.jpg | PRED=b ✅ | 1.32s
[1779/6714] test_1779.jpg | PRED=b ✅ | 1.22s
[1780/6714] test_1780.jpg | PRED=b ✅ | 1.31s
[1781/6714] test_1781.jpg | PRED=c ✅ | 1.22s
[1782/6714] test_1782.jpg | PRED=c ✅ | 1.22s
[1783/6714] test_1783.jpg | PRED=a ✅ | 1.22s
[1784/6714] test_1784.jpg | PRED=b ✅ | 1.22s
[1785/6714] test_1785.jpg | PRED=b ✅ | 1.34s
[1786/6714] test_1786.jpg | PRED=d ✅ | 1.33s
[1787/6714] test_1787.jpg | PRED=c ✅ | 1.22s
[1788/6714] test_1788.jpg | PRED=b ✅ | 1.22s
[1789/6714] test_1789.jpg | PRED=d ✅ | 1.14s
[1790/6714] test_1790.jpg | PRED=d ✅ | 1.23s
[1791/6714] test_1791.jpg | PRED=b ✅ | 1.26s
[1792/6714] test_1792.jpg | PRED=d ✅ | 1.22s
[1793/6714] test_1793.jpg | PRED=c ✅ | 1.24s
[1794/6714] test_1794.jpg | PRED=c ✅ | 1.23s
[1795/6714] test_1795.jpg | PRED=b ✅ | 1.22s
[1796/6714] test_1796.jpg | PRED=c ✅ | 1.23s
[1797/6714] test_1797.jpg | PRED=a ✅ | 1.23s
[1798/6714] test_1798.jpg | PRED=a ✅ | 1.45s
[1799/6714] test_1799.jpg | PRED=b ✅ | 1.22s
[1800/6714] test_1800.jpg | PRED=a ✅ | 1.21s
[1801/6714] test_1801.jpg | PRED=a ✅ | 1.14s
[1802/6714] test_1802.jpg | PRED=c ✅ | 1.24s
[1803/6714] test_1803.jpg | PRED=a ✅ | 1.25s
[1804/6714] test_1804.jpg | PRED=d ✅ | 1.33s
[1805/6714] test_1805.jpg | PRED=d ✅ | 1.22s
[1806/6714] test_1806.jpg | PRED=b ✅ | 1.34s
[1807/6714] test_1807.jpg | PRED=a ✅ | 1.23s
[1808/6714] test_1808.jpg | PRED=c ✅ | 1.39s
[1809/6714] test_1809.jpg | PRED=b ✅ | 1.22s
[1810/6714] test_1810.jpg | PRED=d ✅ | 1.33s
[1811/6714] test_1811.jpg | PRED=d ✅ | 1.22s
[1812/6714] test_1812.jpg | PRED=d ✅ | 1.22s
[1813/6714] test_1813.jpg | PRED=b ✅ | 1.22s
[1814/6714] test_1814.jpg | PRED=c ✅ | 1.21s
[1815/6714] test_1815.jpg | PRED=c ✅ | 1.32s
[1816/6714] test_1816.jpg | PRED=c ✅ | 1.23s
[1817/6714] test_1817.jpg | PRED=d ✅ | 1.32s
[1818/6714] test_1818.jpg | PRED=c ✅ | 1.47s
[1819/6714] test_1819.jpg | PRED=b ✅ | 1.24s
[1820/6714] test_1820.jpg | PRED=d ✅ | 1.22s
[1821/6714] test_1821.jpg | PRED=c ✅ | 1.33s
[1822/6714] test_1822.jpg | PRED=a ✅ | 1.24s
[1823/6714] test_1823.jpg | PRED=c ✅ | 1.23s
[1824/6714] test_1824.jpg | PRED=a ✅ | 1.18s
[1825/6714] test_1825.jpg | PRED=a ✅ | 1.33s
[1826/6714] test_1826.jpg | PRED=a ✅ | 1.34s
[1827/6714] test_1827.jpg | PRED=c ✅ | 1.23s
[1828/6714] test_1828.jpg | PRED=d ✅ | 1.23s
[1829/6714] test_1829.jpg | PRED=d ✅ | 1.45s
[1830/6714] test_1830.jpg | PRED=b ✅ | 1.24s
[1831/6714] test_1831.jpg | PRED=c ✅ | 1.22s
[1832/6714] test_1832.jpg | PRED=c ✅ | 1.34s
[1833/6714] test_1833.jpg | PRED=d ✅ | 1.21s
[1834/6714] test_1834.jpg | PRED=b ✅ | 1.22s
[1835/6714] test_1835.jpg | PRED=c ✅ | 1.23s
[1836/6714] test_1836.jpg | PRED=d ✅ | 1.23s
[1837/6714] test_1837.jpg | PRED=b ✅ | 1.23s
[1838/6714] test_1838.jpg | PRED=c ✅ | 1.23s
[1839/6714] test_1839.jpg | PRED=a ✅ | 1.21s
[1840/6714] test_1840.jpg | PRED=c ✅ | 1.22s
[1841/6714] test_1841.jpg | PRED=b ✅ | 1.23s
[1842/6714] test_1842.jpg | PRED=a ✅ | 1.24s
[1843/6714] test_1843.jpg | PRED=d ✅ | 1.23s
[1844/6714] test_1844.jpg | PRED=b ✅ | 1.34s
[1845/6714] test_1845.jpg | PRED=a ✅ | 1.22s
[1846/6714] test_1846.jpg | PRED=c ✅ | 1.16s
[1847/6714] test_1847.jpg | PRED=d ✅ | 1.23s
[1848/6714] test_1848.jpg | PRED=c ✅ | 1.25s
[1849/6714] test_1849.jpg | PRED=b ✅ | 1.24s
[1850/6714] test_1850.jpg | PRED=b ✅ | 1.23s
[1851/6714] test_1851.jpg | PRED=a ✅ | 1.24s
[1852/6714] test_1852.jpg | PRED=a ✅ | 1.22s
[1853/6714] test_1853.jpg | PRED=c ✅ | 1.23s
[1854/6714] test_1854.jpg | PRED=d ✅ | 1.22s
[1855/6714] test_1855.jpg | PRED=d ✅ | 1.32s
[1856/6714] test_1856.jpg | PRED=a ✅ | 1.15s
[1857/6714] test_1857.jpg | PRED=c ✅ | 1.24s
[1858/6714] test_1858.jpg | PRED=d ✅ | 1.43s
[1859/6714] test_1859.jpg | PRED=c ✅ | 1.25s
[1860/6714] test_1860.jpg | PRED=b ✅ | 1.24s
[1861/6714] test_1861.jpg | PRED=c ✅ | 1.35s
[1862/6714] test_1862.jpg | PRED=b ✅ | 1.22s
[1863/6714] test_1863.jpg | PRED=a ✅ | 1.25s
[1864/6714] test_1864.jpg | PRED=c ✅ | 1.22s
[1865/6714] test_1865.jpg | PRED=b ✅ | 1.22s
[1866/6714] test_1866.jpg | PRED=b ✅ | 1.24s
[1867/6714] test_1867.jpg | PRED=c ✅ | 1.22s
[1868/6714] test_1868.jpg | PRED=c ✅ | 1.23s
[1869/6714] test_1869.jpg | PRED=d ✅ | 1.26s
[1870/6714] test_1870.jpg | PRED=b ✅ | 1.25s
[1871/6714] test_1871.jpg | PRED=a ✅ | 1.21s
[1872/6714] test_1872.jpg | PRED=a ✅ | 1.22s
[1873/6714] test_1873.jpg | PRED=d ✅ | 1.22s
[1874/6714] test_1874.jpg | PRED=c ✅ | 1.23s
[1875/6714] test_1875.jpg | PRED=d ✅ | 1.24s
[1876/6714] test_1876.jpg | PRED=d ✅ | 1.24s
[1877/6714] test_1877.jpg | PRED=c ✅ | 1.23s
[1878/6714] test_1878.jpg | PRED=d ✅ | 1.22s
[1879/6714] test_1879.jpg | PRED=d ✅ | 1.21s
[1880/6714] test_1880.jpg | PRED=b ✅ | 1.24s
[1881/6714] test_1881.jpg | PRED=d ✅ | 1.22s
[1882/6714] test_1882.jpg | PRED=a ✅ | 1.23s
[1883/6714] test_1883.jpg | PRED=b ✅ | 1.21s
[1884/6714] test_1884.jpg | PRED=d ✅ | 1.23s
[1885/6714] test_1885.jpg | PRED=c ✅ | 1.22s
[1886/6714] test_1886.jpg | PRED=d ✅ | 1.24s
[1887/6714] test_1887.jpg | PRED=c ✅ | 1.22s
[1888/6714] test_1888.jpg | PRED=b ✅ | 1.22s
[1889/6714] test_1889.jpg | PRED=a ✅ | 1.23s
[1890/6714] test_1890.jpg | PRED=a ✅ | 1.22s
[1891/6714] test_1891.jpg | PRED=b ✅ | 1.23s
[1892/6714] test_1892.jpg | PRED=b ✅ | 1.22s
[1893/6714] test_1893.jpg | PRED=d ✅ | 1.21s
[1894/6714] test_1894.jpg | PRED=b ✅ | 1.23s
[1895/6714] test_1895.jpg | PRED=b ✅ | 1.22s
[1896/6714] test_1896.jpg | PRED=a ✅ | 1.24s
[1897/6714] test_1897.jpg | PRED=d ✅ | 1.21s
[1898/6714] test_1898.jpg | PRED=c ✅ | 1.23s
[1899/6714] test_1899.jpg | PRED=d ✅ | 1.23s
[1900/6714] test_1900.jpg | PRED=c ✅ | 1.43s
[1901/6714] test_1901.jpg | PRED=d ✅ | 1.21s
[1902/6714] test_1902.jpg | PRED=d ✅ | 1.21s
[1903/6714] test_1903.jpg | PRED=b ✅ | 1.23s
[1904/6714] test_1904.jpg | PRED=a ✅ | 1.23s
[1905/6714] test_1905.jpg | PRED=d ✅ | 1.21s
[1906/6714] test_1906.jpg | PRED=d ✅ | 1.23s
[1907/6714] test_1907.jpg | PRED=a ✅ | 1.32s
[1908/6714] test_1908.jpg | PRED=c ✅ | 1.35s
[1909/6714] test_1909.jpg | PRED=c ✅ | 1.21s
[1910/6714] test_1910.jpg | PRED=b ✅ | 1.22s
[1911/6714] test_1911.jpg | PRED=a ✅ | 1.22s
[1912/6714] test_1912.jpg | PRED=b ✅ | 1.23s
[1913/6714] test_1913.jpg | PRED=d ✅ | 1.21s
[1914/6714] test_1914.jpg | PRED=b ✅ | 1.22s
[1915/6714] test_1915.jpg | PRED=d ✅ | 1.24s
[1916/6714] test_1916.jpg | PRED=a ✅ | 1.21s
[1917/6714] test_1917.jpg | PRED=c ✅ | 1.33s
[1918/6714] test_1918.jpg | PRED=a ✅ | 1.24s
[1919/6714] test_1919.jpg | PRED=a ✅ | 1.24s
[1920/6714] test_1920.jpg | PRED=b ✅ | 1.20s
[1921/6714] test_1921.jpg | PRED=d ✅ | 1.15s
[1922/6714] test_1922.jpg | PRED=a ✅ | 1.23s
[1923/6714] test_1923.jpg | PRED=d ✅ | 1.22s
[1924/6714] test_1924.jpg | PRED=b ✅ | 1.15s
[1925/6714] test_1925.jpg | PRED=d ✅ | 1.22s
[1926/6714] test_1926.jpg | PRED=a ✅ | 1.26s
[1927/6714] test_1927.jpg | PRED=b ✅ | 1.25s
[1928/6714] test_1928.jpg | PRED=c ✅ | 1.21s
[1929/6714] test_1929.jpg | PRED=a ✅ | 1.23s
[1930/6714] test_1930.jpg | PRED=c ✅ | 1.25s
[1931/6714] test_1931.jpg | PRED=b ✅ | 1.23s
[1932/6714] test_1932.jpg | PRED=a ✅ | 1.16s
[1933/6714] test_1933.jpg | PRED=d ✅ | 1.22s
[1934/6714] test_1934.jpg | PRED=a ✅ | 1.31s
[1935/6714] test_1935.jpg | PRED=a ✅ | 1.22s
[1936/6714] test_1936.jpg | PRED=a ✅ | 1.24s
[1937/6714] test_1937.jpg | PRED=d ✅ | 1.21s
[1938/6714] test_1938.jpg | PRED=d ✅ | 1.34s
[1939/6714] test_1939.jpg | PRED=d ✅ | 1.23s
[1940/6714] test_1940.jpg | PRED=b ✅ | 1.23s
[1941/6714] test_1941.jpg | PRED=b ✅ | 1.27s
[1942/6714] test_1942.jpg | PRED=a ✅ | 1.23s
[1943/6714] test_1943.jpg | PRED=d ✅ | 1.22s
[1944/6714] test_1944.jpg | PRED=a ✅ | 1.23s
[1945/6714] test_1945.jpg | PRED=d ✅ | 1.23s
[1946/6714] test_1946.jpg | PRED=b ✅ | 1.23s
[1947/6714] test_1947.jpg | PRED=a ✅ | 1.23s
[1948/6714] test_1948.jpg | PRED=a ✅ | 1.33s
[1949/6714] test_1949.jpg | PRED=d ✅ | 1.22s
[1950/6714] test_1950.jpg | PRED=c ✅ | 1.19s
[1951/6714] test_1951.jpg | PRED=d ✅ | 1.27s
[1952/6714] test_1952.jpg | PRED=b ✅ | 1.22s
[1953/6714] test_1953.jpg | PRED=a ✅ | 1.22s
[1954/6714] test_1954.jpg | PRED=d ✅ | 1.21s
[1955/6714] test_1955.jpg | PRED=a ✅ | 1.22s
[1956/6714] test_1956.jpg | PRED=c ✅ | 1.32s
[1957/6714] test_1957.jpg | PRED=a ✅ | 1.23s
[1958/6714] test_1958.jpg | PRED=c ✅ | 1.23s
[1959/6714] test_1959.jpg | PRED=c ✅ | 1.23s
[1960/6714] test_1960.jpg | PRED=b ✅ | 1.24s
[1961/6714] test_1961.jpg | PRED=d ✅ | 1.22s
[1962/6714] test_1962.jpg | PRED=a ✅ | 1.23s
[1963/6714] test_1963.jpg | PRED=c ✅ | 1.22s
[1964/6714] test_1964.jpg | PRED=b ✅ | 1.23s
[1965/6714] test_1965.jpg | PRED=c ✅ | 1.21s
[1966/6714] test_1966.jpg | PRED=b ✅ | 1.23s
[1967/6714] test_1967.jpg | PRED=b ✅ | 1.16s
[1968/6714] test_1968.jpg | PRED=b ✅ | 1.21s
[1969/6714] test_1969.jpg | PRED=d ✅ | 1.23s
[1970/6714] test_1970.jpg | PRED=c ✅ | 1.33s
[1971/6714] test_1971.jpg | PRED=c ✅ | 1.23s
[1972/6714] test_1972.jpg | PRED=d ✅ | 1.24s
[1973/6714] test_1973.jpg | PRED=d ✅ | 1.23s
[1974/6714] test_1974.jpg | PRED=d ✅ | 1.25s
[1975/6714] test_1975.jpg | PRED=c ✅ | 1.22s
[1976/6714] test_1976.jpg | PRED=c ✅ | 1.18s
[1977/6714] test_1977.jpg | PRED=a ✅ | 1.23s
[1978/6714] test_1978.jpg | PRED=a ✅ | 1.22s
[1979/6714] test_1979.jpg | PRED=b ✅ | 1.23s
[1980/6714] test_1980.jpg | PRED=c ✅ | 1.15s
[1981/6714] test_1981.jpg | PRED=a ✅ | 1.24s
[1982/6714] test_1982.jpg | PRED=c ✅ | 1.29s
[1983/6714] test_1983.jpg | PRED=b ✅ | 1.24s
[1984/6714] test_1984.jpg | PRED=d ✅ | 1.22s
[1985/6714] test_1985.jpg | PRED=d ✅ | 1.22s
[1986/6714] test_1986.jpg | PRED=c ✅ | 1.22s
[1987/6714] test_1987.jpg | PRED=d ✅ | 1.27s
[1988/6714] test_1988.jpg | PRED=b ✅ | 1.21s
[1989/6714] test_1989.jpg | PRED=c ✅ | 1.21s
[1990/6714] test_1990.jpg | PRED=c ✅ | 1.19s
[1991/6714] test_1991.jpg | PRED=b ✅ | 1.31s
[1992/6714] test_1992.jpg | PRED=d ✅ | 1.15s
[1993/6714] test_1993.jpg | PRED=c ✅ | 1.15s
[1994/6714] test_1994.jpg | PRED=a ✅ | 1.23s
[1995/6714] test_1995.jpg | PRED=a ✅ | 1.23s
[1996/6714] test_1996.jpg | PRED=d ✅ | 1.23s
[1997/6714] test_1997.jpg | PRED=c ✅ | 1.33s
[1998/6714] test_1998.jpg | PRED=c ✅ | 1.23s
[1999/6714] test_1999.jpg | PRED=c ✅ | 1.23s
[2000/6714] test_2000.jpg | PRED=a ✅ | 1.24s
[2001/6714] test_2001.jpg | PRED=c ✅ | 1.22s
[2002/6714] test_2002.jpg | PRED=a ✅ | 1.14s
[2003/6714] test_2003.jpg | PRED=a ✅ | 1.23s
[2004/6714] test_2004.jpg | PRED=b ✅ | 1.22s
[2005/6714] test_2005.jpg | PRED=b ✅ | 1.24s
[2006/6714] test_2006.jpg | PRED=a ✅ | 1.24s
[2007/6714] test_2007.jpg | PRED=d ✅ | 1.33s
[2008/6714] test_2008.jpg | PRED=a ✅ | 1.22s
[2009/6714] test_2009.jpg | PRED=b ✅ | 1.22s
[2010/6714] test_2010.jpg | PRED=c ✅ | 1.22s
[2011/6714] test_2011.jpg | PRED=d ✅ | 1.22s
[2012/6714] test_2012.jpg | PRED=b ✅ | 1.24s
[2013/6714] test_2013.jpg | PRED=b ✅ | 1.22s
[2014/6714] test_2014.jpg | PRED=a ✅ | 1.15s
[2015/6714] test_2015.jpg | PRED=b ✅ | 1.24s
[2016/6714] test_2016.jpg | PRED=c ✅ | 1.31s
[2017/6714] test_2017.jpg | PRED=d ✅ | 1.34s
[2018/6714] test_2018.jpg | PRED=c ✅ | 1.34s
[2019/6714] test_2019.jpg | PRED=d ✅ | 1.22s
[2020/6714] test_2020.jpg | PRED=c ✅ | 1.23s
[2021/6714] test_2021.jpg | PRED=d ✅ | 1.22s
[2022/6714] test_2022.jpg | PRED=c ✅ | 1.21s
[2023/6714] test_2023.jpg | PRED=a ✅ | 1.23s
[2024/6714] test_2024.jpg | PRED=b ✅ | 1.25s
[2025/6714] test_2025.jpg | PRED=a ✅ | 1.25s
[2026/6714] test_2026.jpg | PRED=c ✅ | 1.25s
[2027/6714] test_2027.jpg | PRED=d ✅ | 1.22s
[2028/6714] test_2028.jpg | PRED=b ✅ | 1.22s
[2029/6714] test_2029.jpg | PRED=d ✅ | 1.24s
[2030/6714] test_2030.jpg | PRED=c ✅ | 1.32s
[2031/6714] test_2031.jpg | PRED=c ✅ | 1.21s
[2032/6714] test_2032.jpg | PRED=a ✅ | 1.22s
[2033/6714] test_2033.jpg | PRED=b ✅ | 1.57s
[2034/6714] test_2034.jpg | PRED=b ✅ | 1.24s
[2035/6714] test_2035.jpg | PRED=d ✅ | 1.23s
[2036/6714] test_2036.jpg | PRED=a ✅ | 1.25s
[2037/6714] test_2037.jpg | PRED=c ✅ | 1.25s
[2038/6714] test_2038.jpg | PRED=c ✅ | 1.23s
[2039/6714] test_2039.jpg | PRED=b ✅ | 1.33s
[2040/6714] test_2040.jpg | PRED=a ✅ | 1.23s
[2041/6714] test_2041.jpg | PRED=c ✅ | 1.23s
[2042/6714] test_2042.jpg | PRED=d ✅ | 1.24s
[2043/6714] test_2043.jpg | PRED=c ✅ | 1.32s
[2044/6714] test_2044.jpg | PRED=a ✅ | 1.23s
[2045/6714] test_2045.jpg | PRED=a ✅ | 1.21s
[2046/6714] test_2046.jpg | PRED=a ✅ | 1.23s
[2047/6714] test_2047.jpg | PRED=c ✅ | 1.23s
[2048/6714] test_2048.jpg | PRED=c ✅ | 1.23s
[2049/6714] test_2049.jpg | PRED=c ✅ | 1.22s
[2050/6714] test_2050.jpg | PRED=b ✅ | 1.22s
[2051/6714] test_2051.jpg | PRED=b ✅ | 1.21s
[2052/6714] test_2052.jpg | PRED=d ✅ | 1.22s
[2053/6714] test_2053.jpg | PRED=c ✅ | 1.23s
[2054/6714] test_2054.jpg | PRED=d ✅ | 1.24s
[2055/6714] test_2055.jpg | PRED=d ✅ | 1.22s
[2056/6714] test_2056.jpg | PRED=d ✅ | 1.41s
[2057/6714] test_2057.jpg | PRED=b ✅ | 1.21s
[2058/6714] test_2058.jpg | PRED=b ✅ | 1.23s
[2059/6714] test_2059.jpg | PRED=a ✅ | 1.23s
[2060/6714] test_2060.jpg | PRED=a ✅ | 1.22s
[2061/6714] test_2061.jpg | PRED=c ✅ | 1.22s
[2062/6714] test_2062.jpg | PRED=c ✅ | 1.23s
[2063/6714] test_2063.jpg | PRED=a ✅ | 1.22s
[2064/6714] test_2064.jpg | PRED=b ✅ | 1.22s
[2065/6714] test_2065.jpg | PRED=b ✅ | 1.39s
[2066/6714] test_2066.jpg | PRED=d ✅ | 1.22s
[2067/6714] test_2067.jpg | PRED=d ✅ | 1.19s
[2068/6714] test_2068.jpg | PRED=c ✅ | 1.32s
[2069/6714] test_2069.jpg | PRED=a ✅ | 1.21s
[2070/6714] test_2070.jpg | PRED=a ✅ | 1.31s
[2071/6714] test_2071.jpg | PRED=d ✅ | 1.22s
[2072/6714] test_2072.jpg | PRED=a ✅ | 1.22s
[2073/6714] test_2073.jpg | PRED=a ✅ | 1.23s
[2074/6714] test_2074.jpg | PRED=c ✅ | 1.24s
[2075/6714] test_2075.jpg | PRED=b ✅ | 1.23s
[2076/6714] test_2076.jpg | PRED=b ✅ | 1.23s
[2077/6714] test_2077.jpg | PRED=d ✅ | 1.28s
[2078/6714] test_2078.jpg | PRED=b ✅ | 1.23s
[2079/6714] test_2079.jpg | PRED=d ✅ | 1.22s
[2080/6714] test_2080.jpg | PRED=c ✅ | 1.23s
[2081/6714] test_2081.jpg | PRED=a ✅ | 1.22s
[2082/6714] test_2082.jpg | PRED=d ✅ | 1.22s
[2083/6714] test_2083.jpg | PRED=d ✅ | 1.23s
[2084/6714] test_2084.jpg | PRED=a ✅ | 1.41s
[2085/6714] test_2085.jpg | PRED=b ✅ | 1.22s
[2086/6714] test_2086.jpg | PRED=b ✅ | 1.22s
[2087/6714] test_2087.jpg | PRED=d ✅ | 1.23s
[2088/6714] test_2088.jpg | PRED=b ✅ | 1.22s
[2089/6714] test_2089.jpg | PRED=a ✅ | 1.21s
[2090/6714] test_2090.jpg | PRED=a ✅ | 1.24s
[2091/6714] test_2091.jpg | PRED=d ✅ | 1.33s
[2092/6714] test_2092.jpg | PRED=a ✅ | 1.22s
[2093/6714] test_2093.jpg | PRED=b ✅ | 1.19s
[2094/6714] test_2094.jpg | PRED=d ✅ | 1.25s
[2095/6714] test_2095.jpg | PRED=b ✅ | 1.23s
[2096/6714] test_2096.jpg | PRED=b ✅ | 1.34s
[2097/6714] test_2097.jpg | PRED=c ✅ | 1.42s
[2098/6714] test_2098.jpg | PRED=a ✅ | 1.35s
[2099/6714] test_2099.jpg | PRED=d ✅ | 1.25s
[2100/6714] test_2100.jpg | PRED=c ✅ | 1.22s
[2101/6714] test_2101.jpg | PRED=d ✅ | 1.21s
[2102/6714] test_2102.jpg | PRED=c ✅ | 1.22s
[2103/6714] test_2103.jpg | PRED=d ✅ | 1.24s
[2104/6714] test_2104.jpg | PRED=d ✅ | 1.22s
[2105/6714] test_2105.jpg | PRED=d ✅ | 1.23s
[2106/6714] test_2106.jpg | PRED=c ✅ | 1.22s
[2107/6714] test_2107.jpg | PRED=d ✅ | 1.23s
[2108/6714] test_2108.jpg | PRED=c ✅ | 1.21s
[2109/6714] test_2109.jpg | PRED=a ✅ | 1.24s
[2110/6714] test_2110.jpg | PRED=c ✅ | 1.33s
[2111/6714] test_2111.jpg | PRED=b ✅ | 1.33s
[2112/6714] test_2112.jpg | PRED=d ✅ | 1.23s
[2113/6714] test_2113.jpg | PRED=d ✅ | 1.42s
[2114/6714] test_2114.jpg | PRED=a ✅ | 1.22s
[2115/6714] test_2115.jpg | PRED=d ✅ | 1.26s
[2116/6714] test_2116.jpg | PRED=d ✅ | 1.23s
[2117/6714] test_2117.jpg | PRED=d ✅ | 1.33s
[2118/6714] test_2118.jpg | PRED=b ✅ | 1.24s
[2119/6714] test_2119.jpg | PRED=d ✅ | 1.22s
[2120/6714] test_2120.jpg | PRED=d ✅ | 1.22s
[2121/6714] test_2121.jpg | PRED=c ✅ | 1.23s
[2122/6714] test_2122.jpg | PRED=d ✅ | 1.22s
[2123/6714] test_2123.jpg | PRED=a ✅ | 1.23s
[2124/6714] test_2124.jpg | PRED=d ✅ | 1.23s
[2125/6714] test_2125.jpg | PRED=d ✅ | 1.25s
[2126/6714] test_2126.jpg | PRED=a ✅ | 1.24s
[2127/6714] test_2127.jpg | PRED=d ✅ | 1.31s
[2128/6714] test_2128.jpg | PRED=a ✅ | 1.22s
[2129/6714] test_2129.jpg | PRED=c ✅ | 1.21s
[2130/6714] test_2130.jpg | PRED=a ✅ | 1.24s
[2131/6714] test_2131.jpg | PRED=b ✅ | 1.21s
[2132/6714] test_2132.jpg | PRED=b ✅ | 1.23s
[2133/6714] test_2133.jpg | PRED=a ✅ | 1.22s
[2134/6714] test_2134.jpg | PRED=c ✅ | 1.24s
[2135/6714] test_2135.jpg | PRED=a ✅ | 1.22s
[2136/6714] test_2136.jpg | PRED=b ✅ | 1.22s
[2137/6714] test_2137.jpg | PRED=a ✅ | 1.15s
[2138/6714] test_2138.jpg | PRED=a ✅ | 1.24s
[2139/6714] test_2139.jpg | PRED=d ✅ | 1.22s
[2140/6714] test_2140.jpg | PRED=a ✅ | 1.23s
[2141/6714] test_2141.jpg | PRED=c ✅ | 1.24s
[2142/6714] test_2142.jpg | PRED=c ✅ | 1.22s
[2143/6714] test_2143.jpg | PRED=b ✅ | 1.22s
[2144/6714] test_2144.jpg | PRED=c ✅ | 1.23s
[2145/6714] test_2145.jpg | PRED=a ✅ | 1.15s
[2146/6714] test_2146.jpg | PRED=c ✅ | 1.23s
[2147/6714] test_2147.jpg | PRED=d ✅ | 1.21s
[2148/6714] test_2148.jpg | PRED=a ✅ | 1.22s
[2149/6714] test_2149.jpg | PRED=a ✅ | 1.22s
[2150/6714] test_2150.jpg | PRED=c ✅ | 1.23s
[2151/6714] test_2151.jpg | PRED=c ✅ | 1.32s
[2152/6714] test_2152.jpg | PRED=d ✅ | 1.23s
[2153/6714] test_2153.jpg | PRED=a ✅ | 1.34s
[2154/6714] test_2154.jpg | PRED=d ✅ | 1.23s
[2155/6714] test_2155.jpg | PRED=a ✅ | 1.23s
[2156/6714] test_2156.jpg | PRED=a ✅ | 1.24s
[2157/6714] test_2157.jpg | PRED=d ✅ | 1.22s
[2158/6714] test_2158.jpg | PRED=d ✅ | 1.22s
[2159/6714] test_2159.jpg | PRED=b ✅ | 1.21s
[2160/6714] test_2160.jpg | PRED=a ✅ | 1.24s
[2161/6714] test_2161.jpg | PRED=d ✅ | 1.22s
[2162/6714] test_2162.jpg | PRED=d ✅ | 1.16s
[2163/6714] test_2163.jpg | PRED=d ✅ | 1.23s
[2164/6714] test_2164.jpg | PRED=b ✅ | 1.22s
[2165/6714] test_2165.jpg | PRED=c ✅ | 1.14s
[2166/6714] test_2166.jpg | PRED=c ✅ | 1.24s
[2167/6714] test_2167.jpg | PRED=d ✅ | 1.24s
[2168/6714] test_2168.jpg | PRED=c ✅ | 1.25s
[2169/6714] test_2169.jpg | PRED=a ✅ | 1.34s

,idx,id,path,error
5985,5985,test_5986.jpg,test/test_5986.jpg,VLLMValidationError('The decoder prompt (lengt...
6686,6686,test_6687.jpg,test/test_6687.jpg,VLLMValidationError('The decoder prompt (lengt...

ANSWER DISTRIBUTION:
image_only_answer
a    1700
b    1678
c    1650
d    1684
Name: count, dtype: int64

## Step 3-2. 오류 샘플 재추론 및 Submission 생성

전체 Test 6,714개 중 6,712개가 정상적으로 추론되었으며,
2개 샘플에서 입력 길이가 `max_model_len=2048`을 초과하여 오류가 발생했다.

오류가 발생한 2개 이미지만 해상도를 축소하여 다시 추론하고,
모든 Test 샘플의 예측값이 a / b / c / d 중 하나인지 최종 검증한다.

이후 `sample_submission.csv`의 id 순서를 그대로 유지하여
최종 제출 파일을 생성한다.

최종 제출 형식:

- id
- answer

In [12]:
# ============================================================
# [STEP 3-2] RETRY 2 ERROR CASES + MAKE SUBMISSION
# ============================================================

import os
import time
import inspect
import pandas as pd

from pathlib import Path
from PIL import Image


# ============================================================
# 0. PATH
# ============================================================

TEST_OUT_CSV = Path(
    "/content/drive/MyDrive/cleaning_data/122b_eval/122b_image_only_test.csv"
)

SUBMISSION_OUT = Path(
    "/content/drive/MyDrive/cleaning_data/122b_eval/122b_submission.csv"
)


# ============================================================
# 1. LOAD CURRENT RESULT
# ============================================================

result_df = pd.read_csv(
    TEST_OUT_CSV
)

error_df = result_df[
    result_df["status"] != "ok"
].copy()


print("=" * 78)
print("ERROR RETRY")
print("=" * 78)

print(
    "ERROR CASES:",
    len(error_df)
)

display(
    error_df[
        [
            "idx",
            "id",
            "path",
            "error",
        ]
    ]
)


# ============================================================
# 2. RETRY ONLY ERROR CASES
#
# 입력 길이 초과 문제이므로
# 이미지 해상도만 줄여 visual token 수 감소
# ============================================================

SUPPORTS_USE_TQDM = (
    "use_tqdm"
    in inspect.signature(
        llm_122b.chat
    ).parameters
)


for _, err_row in error_df.iterrows():

    idx = int(
        err_row["idx"]
    )

    row = test_df.iloc[
        idx
    ]

    image_path = (
        DATA_ROOT
        / str(
            row["path"]
        )
    )

    print(
        "\nRETRY:",
        idx,
        row["id"]
    )


    t0 = time.time()


    try:

        with Image.open(
            image_path
        ) as im:

            image = im.convert(
                "RGB"
            )

            # 원본 비율 유지
            # 긴 변을 최대 1024px로 축소
            image.thumbnail(
                (1024, 1024),
                Image.Resampling.LANCZOS
            )

            image = image.copy()


        print(
            "resized image:",
            image.size
        )


        messages = [

            {
                "role":
                    "system",

                "content":
                    SYSTEM_PROMPT,
            },

            {
                "role":
                    "user",

                "content": [

                    {
                        "type":
                            "image_pil",

                        "image_pil":
                            image,
                    },

                    {
                        "type":
                            "text",

                        "text":
                            build_image_only_prompt(

                                row["question"],

                                row["a"],
                                row["b"],
                                row["c"],
                                row["d"],
                            ),
                    },
                ],
            },
        ]


        kwargs = dict(

            messages=
                messages,

            sampling_params=
                sampling_params_image_only,

            chat_template_kwargs={
                "enable_thinking":
                    False
            },
        )


        if SUPPORTS_USE_TQDM:

            kwargs[
                "use_tqdm"
            ] = False


        outputs = llm_122b.chat(
            **kwargs
        )


        pred = (
            outputs[0]
            .outputs[0]
            .text
            .strip()
            .lower()
        )


        assert pred in {
            "a",
            "b",
            "c",
            "d",
        }


        elapsed = (
            time.time()
            - t0
        )


        # 기존 row 수정
        result_df.loc[
            result_df["idx"] == idx,
            "image_only_answer"
        ] = pred

        result_df.loc[
            result_df["idx"] == idx,
            "elapsed_sec"
        ] = round(
            elapsed,
            4
        )

        result_df.loc[
            result_df["idx"] == idx,
            "status"
        ] = "ok"

        result_df.loc[
            result_df["idx"] == idx,
            "error"
        ] = ""


        print(
            f"✅ {row['id']} -> {pred} "
            f"({elapsed:.2f}s)"
        )


    except Exception as e:

        print(
            "❌ RETRY FAILED:",
            repr(e)
        )


# ============================================================
# 3. SAVE UPDATED FULL RESULT
# ============================================================

result_df = (
    result_df
    .sort_values("idx")
    .reset_index(drop=True)
)

result_df.to_csv(
    TEST_OUT_CSV,
    index=False,
    encoding="utf-8-sig"
)


# ============================================================
# 4. FINAL VALIDATION
# ============================================================

valid_mask = (
    result_df["status"].eq("ok")
    &
    result_df[
        "image_only_answer"
    ]
    .astype(str)
    .str.strip()
    .str.lower()
    .isin(
        ["a", "b", "c", "d"]
    )
)


print("\n" + "=" * 78)
print("FINAL TEST RESULT")
print("=" * 78)

print(
    "TOTAL:",
    len(result_df)
)

print(
    "VALID:",
    int(valid_mask.sum())
)

print(
    "ERROR:",
    int((~valid_mask).sum())
)


assert len(result_df) == len(test_df) == 6714

assert valid_mask.all(), (
    "❌ 아직 정상 답변이 없는 Test 샘플이 있습니다."
)


# ============================================================
# 5. MAKE SUBMISSION
#
# sample_submission의 id 순서를 그대로 사용
# ============================================================

pred_map = dict(
    zip(
        result_df["id"].astype(str),
        result_df[
            "image_only_answer"
        ]
        .astype(str)
        .str.strip()
        .str.lower()
    )
)


submission = (
    sample_submission[
        ["id"]
    ]
    .copy()
)


submission[
    "answer"
] = (
    submission["id"]
    .astype(str)
    .map(
        pred_map
    )
)


# ============================================================
# 6. SUBMISSION VALIDATION
# ============================================================

assert len(submission) == 6714

assert submission[
    "answer"
].notna().all()

assert submission[
    "answer"
].isin(
    ["a", "b", "c", "d"]
).all()

assert (
    submission["id"]
    .astype(str)
    .tolist()
    ==
    sample_submission["id"]
    .astype(str)
    .tolist()
)


# ============================================================
# 7. SAVE
# ============================================================

submission.to_csv(
    SUBMISSION_OUT,
    index=False,
    encoding="utf-8-sig"
)


print("\n" + "=" * 78)
print("SUBMISSION READY")
print("=" * 78)

print(
    "ROWS :",
    len(submission)
)

print(
    "PATH :",
    SUBMISSION_OUT
)

print("\nANSWER DISTRIBUTION:")

print(
    submission[
        "answer"
    ]
    .value_counts()
    .sort_index()
)

print("=" * 78)

display(
    submission.head()
)

==============================================================================
ERROR RETRY
==============================================================================
ERROR CASES: 2

,idx,id,path,error
5985,5985,test_5986.jpg,test/test_5986.jpg,VLLMValidationError('The decoder prompt (lengt...
6686,6686,test_6687.jpg,test/test_6687.jpg,VLLMValidationError('The decoder prompt (lengt...

RETRY: 5985 test_5986.jpg
resized image: (238, 1024)
✅ test_5986.jpg -> b (1.12s)

RETRY: 6686 test_6687.jpg
resized image: (1024, 217)
✅ test_6687.jpg -> d (1.07s)

==============================================================================
FINAL TEST RESULT
==============================================================================
TOTAL: 6714
VALID: 6714
ERROR: 0

==============================================================================
SUBMISSION READY
==============================================================================
ROWS : 6714
PATH : /content/drive/MyDrive/cleaning_data/122b_eval/122b_submission.csv

ANSWER DISTRIBUTION:
answer
a    1700
b    1679
c    1650
d    1685
Name: count, dtype: int64
==============================================================================

              id answer
0  test_0001.jpg      b
1  test_0002.jpg      c
2  test_0003.jpg      d
3  test_0004.jpg      d
4  test_0005.jpg      c